/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/layouts/debugging.inc
 * PURPOSE:
 *   GTK presentation metadata for Framework semantic layout debugging.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_LAYOUT_PROFILE("debugging", "Debug", "studio.layout.debugging", "Run and Debug, Editor, Problems, Output and Terminal")
