/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/layouts/default.inc
 * PURPOSE:
 *   GTK presentation metadata for Framework semantic layout default.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_LAYOUT_PROFILE("default", "Default", "studio.layout.default", "Explorer, Editor, Problems and Output")
