/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/layouts/source_control.inc
 * PURPOSE:
 *   GTK presentation metadata for Framework semantic layout source_control.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_LAYOUT_PROFILE("source_control", "Source", "studio.layout.source-control", "Source Control, Editor, Problems and Output")
