/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/layouts/testing.inc
 * PURPOSE:
 *   GTK presentation metadata for Framework semantic layout testing.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_LAYOUT_PROFILE("testing", "Tests", "studio.layout.testing", "Test Explorer, Editor, Problems and Output")
