/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/app/contributions.c
 *
 * PURPOSE:
 *   Populate Studio pane, action, menu, toolbar, status, contribution and
 *   layout models using toolkit-neutral Framework records. Batch 23 also
 *   exposes one primary-sidebar pane for every unified Activity Bar area.
 *
 * AUTHOR AND ORGANISATION:
 * Sammy Hegab
 * Umicom Foundation
 *
 * LICENCE:
 * MIT
 *---------------------------------------------------------------------------*/

/* BEGINNER NOTE:
 * These records name Studio-specific surfaces. Framework owns how panes are
 * stored, activated, laid out and rendered by headless or GTK4 adapters.
 */

#include "umicom/studio/contributions.h"

#include <string.h>

#include "umicom/document/commands.h"
#include "umicom/studio/commands.h"
#include "umicom/studio/perspectives.h"
#include "umicom/studio/workbench_commands.h"
#include "umicom/studio/workspace_profiles.h"

static const UmiUiPaneSnapshot STUDIO_PANES[] = {
    { UMI_STUDIO_PANE_EXPLORER, "Project Explorer", "studio.project-explorer", "folder-symbolic", UMI_UI_PLACEMENT_LEFT, 10, 1, 1, 1, { 280, 500 } },
    { UMI_STUDIO_PANE_EDITOR, "Editor", "studio.editor-host", "text-x-generic-symbolic", UMI_UI_PLACEMENT_CENTRE, 20, 1, 0, 0, { 760, 500 } },
    { UMI_STUDIO_PANE_OUTPUT, "Output", "studio.output", "utilities-terminal-symbolic", UMI_UI_PLACEMENT_BOTTOM, 30, 1, 1, 1, { 760, 220 } },
    { UMI_STUDIO_PANE_PROBLEMS, "Problems", "studio.problems", "dialog-warning-symbolic", UMI_UI_PLACEMENT_BOTTOM, 40, 1, 1, 1, { 760, 220 } },
    { UMI_STUDIO_PANE_SEARCH, "Search", "studio.search", "system-search-symbolic", UMI_UI_PLACEMENT_LEFT, 50, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_TERMINAL, "Terminal", "studio.terminal", "utilities-terminal-symbolic", UMI_UI_PLACEMENT_BOTTOM, 60, 1, 1, 1, { 760, 240 } },
    { UMI_STUDIO_PANE_PROCESSES, "Processes", "studio.processes", "system-run-symbolic", UMI_UI_PLACEMENT_BOTTOM, 62, 0, 1, 1, { 760, 240 } },
    { UMI_STUDIO_PANE_TASKS, "Tasks", "studio.tasks", "view-list-symbolic", UMI_UI_PLACEMENT_BOTTOM, 64, 0, 1, 1, { 760, 240 } },
    { UMI_STUDIO_PANE_TERMINAL_HISTORY, "Terminal History", "studio.terminal-history", "document-open-recent-symbolic", UMI_UI_PLACEMENT_BOTTOM, 66, 0, 1, 1, { 760, 240 } },
    { UMI_STUDIO_PANE_CHAT, "AI Chat", "studio.ai-chat", "mail-message-new-symbolic", UMI_UI_PLACEMENT_RIGHT, 70, 1, 1, 1, { 360, 500 } },
    { UMI_STUDIO_PANE_ARCHITECTURE, "Architecture", "studio.architecture", "view-grid-symbolic", UMI_UI_PLACEMENT_RIGHT, 80, 0, 1, 1, { 360, 500 } },

    /*
     * Unified primary-sidebar destinations. These are product-facing hosts;
     * later batches can register richer view-model factories behind the same
     * stable pane/view IDs without changing Activity Bar or layout code.
     */
    { UMI_STUDIO_PANE_SOURCE_CONTROL, "Source Control", "studio.source-control", "org.gnome.Builder-vcs-symbolic", UMI_UI_PLACEMENT_LEFT, 90, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_VCS_COMMIT, "Commit", "studio.vcs-commit", "document-save-symbolic", UMI_UI_PLACEMENT_LEFT, 91, 0, 1, 1, { 360, 280 } },
    { UMI_STUDIO_PANE_VCS_HISTORY, "Repository History", "studio.vcs-history", "document-open-recent-symbolic", UMI_UI_PLACEMENT_RIGHT, 92, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_VCS_BRANCHES, "Branches", "studio.vcs-branches", "view-list-tree-symbolic", UMI_UI_PLACEMENT_RIGHT, 93, 0, 1, 1, { 360, 360 } },
    { UMI_STUDIO_PANE_VCS_REMOTES, "Remotes", "studio.vcs-remotes", "network-server-symbolic", UMI_UI_PLACEMENT_RIGHT, 94, 0, 1, 1, { 440, 300 } },
    { UMI_STUDIO_PANE_VCS_CONFLICTS, "Merge Conflicts", "studio.vcs-conflicts", "dialog-warning-symbolic", UMI_UI_PLACEMENT_LEFT, 95, 0, 1, 1, { 380, 300 } },
    { UMI_STUDIO_PANE_VCS_DIFF, "Diff Viewer", "studio.vcs-diff", "document-properties-symbolic", UMI_UI_PLACEMENT_BOTTOM, 96, 0, 1, 1, { 760, 320 } },
    { UMI_STUDIO_PANE_VCS_OPERATIONS, "Source Control Operations", "studio.vcs-operations", "view-history-symbolic", UMI_UI_PLACEMENT_BOTTOM, 97, 0, 1, 1, { 760, 260 } },
    { UMI_STUDIO_PANE_RUN_DEBUG, "Run and Debug", "studio.run-debug", "system-run-symbolic", UMI_UI_PLACEMENT_LEFT, 100, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_DEBUG_CALL_STACK, "Call Stack", "studio.debug-call-stack", "view-list-tree-symbolic", UMI_UI_PLACEMENT_RIGHT, 101, 0, 1, 1, { 380, 300 } },
    { UMI_STUDIO_PANE_DEBUG_VARIABLES, "Variables", "studio.debug-variables", "view-list-symbolic", UMI_UI_PLACEMENT_RIGHT, 102, 0, 1, 1, { 380, 300 } },
    { UMI_STUDIO_PANE_DEBUG_WATCHES, "Watch", "studio.debug-watches", "system-search-symbolic", UMI_UI_PLACEMENT_RIGHT, 103, 0, 1, 1, { 380, 260 } },
    { UMI_STUDIO_PANE_DEBUG_BREAKPOINTS, "Breakpoints", "studio.debug-breakpoints", "media-record-symbolic", UMI_UI_PLACEMENT_LEFT, 104, 0, 1, 1, { 320, 260 } },
    { UMI_STUDIO_PANE_DEBUG_CONSOLE, "Debug Console", "studio.debug-console", "utilities-terminal-symbolic", UMI_UI_PLACEMENT_BOTTOM, 105, 0, 1, 1, { 760, 280 } },
    { UMI_STUDIO_PANE_TESTING, "Testing", "studio.testing", "emblem-ok-symbolic", UMI_UI_PLACEMENT_LEFT, 110, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_TEST_RESULTS, "Test Results", "studio.test-results", "emblem-ok-symbolic", UMI_UI_PLACEMENT_BOTTOM, 111, 0, 1, 1, { 760, 280 } },
    { UMI_STUDIO_PANE_TEST_FAILURES, "Test Failures", "studio.test-failures", "dialog-error-symbolic", UMI_UI_PLACEMENT_BOTTOM, 112, 0, 1, 1, { 760, 320 } },
    { UMI_STUDIO_PANE_TEST_OUTPUT, "Test Output", "studio.test-output", "utilities-terminal-symbolic", UMI_UI_PLACEMENT_BOTTOM, 113, 0, 1, 1, { 760, 300 } },
    { UMI_STUDIO_PANE_TEST_COVERAGE, "Test Coverage", "studio.test-coverage", "view-statistics-symbolic", UMI_UI_PLACEMENT_RIGHT, 114, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_TEST_RUNS, "Test Runs", "studio.test-runs", "document-open-recent-symbolic", UMI_UI_PLACEMENT_RIGHT, 115, 0, 1, 1, { 420, 400 } },
    { UMI_STUDIO_PANE_BUILD_DASHBOARD, "Build Dashboard", "studio.build-dashboard", "system-run-symbolic", UMI_UI_PLACEMENT_LEFT, 116, 0, 1, 1, { 360, 500 } },
    { UMI_STUDIO_PANE_BUILD_GRAPH, "Build Graph", "studio.build-graph", "view-list-tree-symbolic", UMI_UI_PLACEMENT_LEFT, 117, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_BUILD_HISTORY, "Build History", "studio.build-history", "document-open-recent-symbolic", UMI_UI_PLACEMENT_BOTTOM, 118, 0, 1, 1, { 780, 300 } },
    { UMI_STUDIO_PANE_BUILD_OUTPUT, "Build Output", "studio.build-output", "utilities-terminal-symbolic", UMI_UI_PLACEMENT_BOTTOM, 119, 0, 1, 1, { 820, 340 } },
    { UMI_STUDIO_PANE_BUILD_ARTIFACTS, "Build Artifacts", "studio.build-artifacts", "package-x-generic-symbolic", UMI_UI_PLACEMENT_RIGHT, 120, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_BUILD_TASKS, "Build Tasks", "studio.build-tasks", "view-list-symbolic", UMI_UI_PLACEMENT_BOTTOM, 121, 0, 1, 1, { 780, 280 } },
    { UMI_STUDIO_PANE_TRADING_DASHBOARD, "Trading Dashboard", "studio.trading-dashboard", "view-statistics-symbolic", UMI_UI_PLACEMENT_LEFT, 122, 0, 1, 1, { 380, 500 } },
    { UMI_STUDIO_PANE_TRADING_WATCHLIST, "Watchlist", "studio.trading-watchlist", "view-list-symbolic", UMI_UI_PLACEMENT_LEFT, 123, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_TRADING_DEPTH, "Market Depth", "studio.trading-depth", "view-list-tree-symbolic", UMI_UI_PLACEMENT_LEFT, 124, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_TRADING_CHART, "Chart Analytics", "studio.trading-chart", "view-statistics-symbolic", UMI_UI_PLACEMENT_RIGHT, 125, 0, 1, 1, { 680, 520 } },
    { UMI_STUDIO_PANE_TRADING_ORDER_TICKET, "Order Ticket", "studio.trading-order-ticket", "document-edit-symbolic", UMI_UI_PLACEMENT_RIGHT, 126, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_TRADING_ORDERS, "Orders", "studio.trading-orders", "view-list-symbolic", UMI_UI_PLACEMENT_BOTTOM, 127, 0, 1, 1, { 820, 300 } },
    { UMI_STUDIO_PANE_TRADING_EXECUTIONS, "Executions", "studio.trading-executions", "emblem-ok-symbolic", UMI_UI_PLACEMENT_BOTTOM, 128, 0, 1, 1, { 820, 280 } },
    { UMI_STUDIO_PANE_TRADING_PORTFOLIO_RISK, "Portfolio & Risk", "studio.trading-portfolio-risk", "security-high-symbolic", UMI_UI_PLACEMENT_RIGHT, 129, 0, 1, 1, { 480, 520 } },
    { UMI_STUDIO_PANE_DESIGNER, "Designer", "studio.designer", "applications-graphics-symbolic", UMI_UI_PLACEMENT_LEFT, 120, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_APPLICATIONS, "Applications", "studio.application-hub", "view-app-grid-symbolic", UMI_UI_PLACEMENT_LEFT, 130, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_APPLICATION_COMPONENTS, "Application Components", "studio.application-components", "view-grid-symbolic", UMI_UI_PLACEMENT_RIGHT, 131, 0, 1, 1, { 460, 520 } },
    { UMI_STUDIO_PANE_GTK4_COVERAGE, "GTK4 Coverage", "studio.gtk4-coverage", "emblem-system-symbolic", UMI_UI_PLACEMENT_RIGHT, 132, 0, 1, 1, { 460, 520 } },
    { UMI_STUDIO_PANE_FRAMEWORK, "Framework", "studio.framework", "view-grid-symbolic", UMI_UI_PLACEMENT_LEFT, 140, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_AI, "AI / AuthorEngine", "studio.authorengine", "mail-message-new-symbolic", UMI_UI_PLACEMENT_LEFT, 150, 0, 1, 1, { 320, 500 } },
    { UMI_STUDIO_PANE_AI_RUNTIMES, "AI Runtimes", "studio.ai-runtimes", "computer-symbolic", UMI_UI_PLACEMENT_LEFT, 151, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_AI_CONTEXT, "AI Context", "studio.ai-context", "folder-documents-symbolic", UMI_UI_PLACEMENT_LEFT, 152, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_AI_SESSIONS, "AI Sessions", "studio.ai-sessions", "document-open-recent-symbolic", UMI_UI_PLACEMENT_LEFT, 153, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_AI_PRIVACY, "AI Privacy", "studio.ai-privacy", "security-high-symbolic", UMI_UI_PLACEMENT_LEFT, 154, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_AI_CODING, "AI Assistant and Vibe Coding", "studio.ai-coding", "applications-development-symbolic", UMI_UI_PLACEMENT_RIGHT, 155, 0, 1, 1, { 440, 560 } },
    { UMI_STUDIO_PANE_AI_CODING_CONTEXT, "AI Coding Context", "studio.ai-coding-context", "folder-documents-symbolic", UMI_UI_PLACEMENT_LEFT, 156, 0, 1, 1, { 480, 560 } },
    { UMI_STUDIO_PANE_AI_PATCH_REVIEW, "AI Patch Review", "studio.ai-patch-review", "document-properties-symbolic", UMI_UI_PLACEMENT_BOTTOM, 157, 0, 1, 1, { 820, 340 } },
    { UMI_STUDIO_PANE_EXTENSIONS, "Extensions", "studio.extensions-installed", "application-x-addon-symbolic", UMI_UI_PLACEMENT_LEFT, 160, 0, 1, 1, { 380, 500 } },
    { UMI_STUDIO_PANE_EXTENSION_CATALOGUE, "Extension Catalogue", "studio.extensions-catalogue", "system-search-symbolic", UMI_UI_PLACEMENT_LEFT, 161, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_EXTENSION_PERMISSIONS, "Extension Permissions", "studio.extensions-permissions", "security-high-symbolic", UMI_UI_PLACEMENT_LEFT, 162, 0, 1, 1, { 420, 500 } },
    { UMI_STUDIO_PANE_EXTENSION_AUDIT, "Extension Audit", "studio.extensions-audit", "document-open-recent-symbolic", UMI_UI_PLACEMENT_BOTTOM, 163, 0, 1, 1, { 760, 280 } },
    { UMI_STUDIO_PANE_PRODUCT_MARKETPLACE, "Product Marketplace", "studio.product-marketplace", "system-software-install-symbolic", UMI_UI_PLACEMENT_LEFT, 170, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_PRODUCTS_INSTALLED, "Installed Products", "studio.products-installed", "package-x-generic-symbolic", UMI_UI_PLACEMENT_LEFT, 171, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_PRODUCT_UPDATES, "Product Updates", "studio.product-updates", "software-update-available-symbolic", UMI_UI_PLACEMENT_LEFT, 172, 0, 1, 1, { 440, 500 } },
    { UMI_STUDIO_PANE_PRODUCT_TRANSACTIONS, "Distribution Transactions", "studio.product-transactions", "document-open-recent-symbolic", UMI_UI_PLACEMENT_BOTTOM, 173, 0, 1, 1, { 760, 300 } },
    { UMI_STUDIO_PANE_PRODUCT_EVIDENCE, "Supply-chain Evidence", "studio.product-evidence", "security-high-symbolic", UMI_UI_PLACEMENT_BOTTOM, 174, 0, 1, 1, { 760, 300 } }
    ,{ UMI_STUDIO_PANE_KNOWLEDGE, "Knowledge Centre", "studio.knowledge", "folder-documents-symbolic", UMI_UI_PLACEMENT_LEFT, 180, 0, 1, 1, { 440, 540 } }
    ,{ UMI_STUDIO_PANE_KNOWLEDGE_COLLECTIONS, "Knowledge Collections", "studio.knowledge-collections", "view-list-tree-symbolic", UMI_UI_PLACEMENT_LEFT, 181, 0, 1, 1, { 440, 540 } }
    ,{ UMI_STUDIO_PANE_KNOWLEDGE_SOURCES, "Knowledge Sources", "studio.knowledge-sources", "folder-symbolic", UMI_UI_PLACEMENT_LEFT, 182, 0, 1, 1, { 500, 540 } }
    ,{ UMI_STUDIO_PANE_KNOWLEDGE_SEARCH, "Knowledge Search", "studio.knowledge-search", "system-search-symbolic", UMI_UI_PLACEMENT_RIGHT, 183, 0, 1, 1, { 560, 540 } }
    ,{ UMI_STUDIO_PANE_KNOWLEDGE_SOURCE, "Knowledge Source Viewer", "studio.knowledge-source", "text-x-generic-symbolic", UMI_UI_PLACEMENT_BOTTOM, 184, 0, 1, 1, { 820, 340 } }
};

static const UmiUiActionSnapshot STUDIO_ACTIONS[] = {
    { "studio.action.perspective.develop", UMI_STUDIO_COMMAND_PERSPECTIVE_ACTIVATE, "Develop", "Activate Develop perspective", "applications-development-symbolic", "Ctrl+1", 1, 1, 0, 0, 10, UMI_STUDIO_PERSPECTIVE_DEVELOP, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.perspective.build", UMI_STUDIO_COMMAND_PERSPECTIVE_ACTIVATE, "Build", "Activate Build perspective", "system-run-symbolic", "Ctrl+2", 1, 1, 0, 0, 20, UMI_STUDIO_PERSPECTIVE_BUILD, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.perspective.test", UMI_STUDIO_COMMAND_PERSPECTIVE_ACTIVATE, "Test", "Activate Test perspective", "emblem-ok-symbolic", "Ctrl+3", 1, 1, 0, 0, 30, UMI_STUDIO_PERSPECTIVE_TEST, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.explorer", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Project Explorer", "Show or hide Project Explorer", "folder-symbolic", "Ctrl+Shift+E", 1, 1, 1, 1, 40, UMI_STUDIO_PANE_EXPLORER, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.output", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Output", "Show or hide Output", "utilities-terminal-symbolic", "Ctrl+J", 1, 1, 1, 1, 50, UMI_STUDIO_PANE_OUTPUT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.problems", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Problems", "Show or hide Problems", "dialog-warning-symbolic", "Ctrl+Shift+M", 1, 1, 1, 1, 60, UMI_STUDIO_PANE_PROBLEMS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.layout.reset", UMI_STUDIO_COMMAND_LAYOUT_RESET, "Reset Layout", "Restore the default Studio layout", "view-restore-symbolic", "", 1, 1, 0, 0, 70, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.develop", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Develop Layout", "Editor-first coding workspace", "applications-development-symbolic", "", 1, 1, 0, 0, 71, UMI_STUDIO_WORKSPACE_PROFILE_DEVELOP, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.focus", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Focus Layout", "Hide tool regions for distraction-free editing", "view-fullscreen-symbolic", "Ctrl+Shift+F12", 1, 1, 0, 0, 72, UMI_STUDIO_WORKSPACE_PROFILE_FOCUS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.debug", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Debug Layout", "Show source, execution state and debugging tools", "applications-engineering-symbolic", "", 1, 1, 0, 0, 73, UMI_STUDIO_WORKSPACE_PROFILE_DEBUG, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.source-control", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Source Control Layout", "Show changes, commit, history, branches, conflicts, diffs and operations", "org.gnome.Builder-vcs-symbolic", "", 1, 1, 0, 0, 74, UMI_STUDIO_WORKSPACE_PROFILE_SOURCE_CONTROL, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.testing", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Testing Layout", "Show Test Explorer, results, failures, output, coverage and run history", "emblem-ok-symbolic", "", 1, 1, 0, 0, 75, UMI_STUDIO_WORKSPACE_PROFILE_TESTING, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.build", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Build Layout", "Show build dashboard, graph, history, output, artifacts and tasks", "system-run-symbolic", "", 1, 1, 0, 0, 76, UMI_STUDIO_WORKSPACE_PROFILE_BUILD, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.review", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Review Layout", "Show comparison and review context", "document-properties-symbolic", "", 1, 1, 0, 0, 75, UMI_STUDIO_WORKSPACE_PROFILE_REVIEW, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.operations", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Operations Layout", "Show monitoring and operational tools", "utilities-system-monitor-symbolic", "", 1, 1, 0, 0, 76, UMI_STUDIO_WORKSPACE_PROFILE_OPERATIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.workspace-profile.trading", UMI_STUDIO_COMMAND_WORKSPACE_PROFILE_ACTIVATE, "Trading Layout", "Show market, analytics, order and risk tools", "view-statistics-symbolic", "", 1, 1, 0, 0, 77, UMI_STUDIO_WORKSPACE_PROFILE_TRADING, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.notification.info", UMI_STUDIO_COMMAND_NOTIFICATION_INFO, "About This Workbench", "Show Framework workbench information", "dialog-information-symbolic", "", 1, 1, 0, 0, 80, "Umicom Studio 0.17 uses the Framework-owned workbench and Editor Core v2.", UMI_UI_ACTION_ARGUMENT_NONE },

    /* Batch 39 binds the visible IDE vocabulary to canonical Framework
     * document commands. GTK only collects arguments; Framework owns logic. */
    { "studio.action.file.new", UMI_DOCUMENT_COMMAND_NEW, "New File", "Create an untitled editor document", "document-new-symbolic", "Ctrl+N", 1, 1, 0, 0, 100, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.file.open", UMI_DOCUMENT_COMMAND_OPEN, "Open File…", "Open a file in the Framework editor", "document-open-symbolic", "Ctrl+O", 1, 1, 0, 0, 110, "", UMI_UI_ACTION_ARGUMENT_OPEN_PATH },
    { "studio.action.file.save", UMI_DOCUMENT_COMMAND_SAVE, "Save", "Save the active Framework working copy", "document-save-symbolic", "Ctrl+S", 1, 1, 0, 0, 120, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.file.save-as", UMI_DOCUMENT_COMMAND_SAVE_AS, "Save As…", "Save the active document to another path", "document-save-as-symbolic", "Ctrl+Shift+S", 1, 1, 0, 0, 130, "", UMI_UI_ACTION_ARGUMENT_SAVE_PATH },
    { "studio.action.file.close", UMI_DOCUMENT_COMMAND_CLOSE, "Close File", "Close the active document without data loss", "window-close-symbolic", "Ctrl+W", 1, 1, 0, 0, 135, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.close-others", UMI_STUDIO_COMMAND_EDITOR_CLOSE_OTHERS, "Close Other Editors", "Close clean, unpinned editors in this group", "window-close-symbolic", "", 1, 1, 0, 0, 136, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.close-all", UMI_STUDIO_COMMAND_EDITOR_CLOSE_ALL, "Close All Editors", "Close clean, unpinned editors without losing changes", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 137, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.pin-toggle", UMI_STUDIO_COMMAND_EDITOR_PIN_TOGGLE, "Pin or Unpin Editor", "Keep the active editor open across close operations", "view-pin-symbolic", "", 1, 1, 1, 0, 138, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.keep-preview", UMI_STUDIO_COMMAND_EDITOR_PREVIEW_PROMOTE, "Keep Preview Editor", "Promote a preview into a permanent editor", "emblem-favorite-symbolic", "", 1, 1, 0, 0, 139, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.edit.undo", UMI_DOCUMENT_COMMAND_UNDO, "Undo", "Undo the latest editor transaction", "edit-undo-symbolic", "Ctrl+Z", 1, 1, 0, 0, 140, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.edit.redo", UMI_DOCUMENT_COMMAND_REDO, "Redo", "Redo the latest editor transaction", "edit-redo-symbolic", "Ctrl+Shift+Z", 1, 1, 0, 0, 150, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.edit.find", UMI_DOCUMENT_COMMAND_FIND, "Find", "Find text in the active editor", "edit-find-symbolic", "Ctrl+F", 1, 1, 0, 0, 160, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.edit.replace", UMI_DOCUMENT_COMMAND_REPLACE, "Replace", "Replace text in the active editor", "edit-find-replace-symbolic", "Ctrl+H", 1, 1, 0, 0, 170, "", UMI_UI_ACTION_ARGUMENT_FIND_REPLACE },
    { "studio.action.view.command-palette", UMI_STUDIO_COMMAND_QUICK_ACCESS_SHOW, "Command Palette…", "Search and execute registered Studio actions and Framework commands", "system-search-symbolic", "Ctrl+Shift+P", 1, 1, 0, 0, 180, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.word-wrap", UMI_STUDIO_COMMAND_EDITOR_WORD_WRAP_TOGGLE, "Toggle Word Wrap", "Wrap long lines within the editor viewport", "format-justify-left-symbolic", "Alt+Z", 1, 1, 1, 0, 181, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.next", UMI_STUDIO_COMMAND_EDITOR_NEXT, "Next Editor", "Activate the next editor tab", "go-next-symbolic", "Ctrl+Tab", 1, 1, 0, 0, 182, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.previous", UMI_STUDIO_COMMAND_EDITOR_PREVIOUS, "Previous Editor", "Activate the previous editor tab", "go-previous-symbolic", "Ctrl+Shift+Tab", 1, 1, 0, 0, 183, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.split-right", UMI_STUDIO_COMMAND_EDITOR_SPLIT_RIGHT, "Split Editor Right", "Create a side-by-side editor group", "view-grid-symbolic", "Ctrl+\\", 1, 1, 0, 0, 184, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.split-down", UMI_STUDIO_COMMAND_EDITOR_SPLIT_DOWN, "Split Editor Down", "Create a stacked editor group", "view-grid-symbolic", "Ctrl+Shift+\\", 1, 1, 0, 0, 185, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.move-next-group", UMI_STUDIO_COMMAND_EDITOR_MOVE_NEXT_GROUP, "Move Editor to Next Group", "Move the active tab into the other editor group", "go-next-symbolic", "Ctrl+Alt+Right", 1, 1, 0, 0, 186, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.move-previous-group", UMI_STUDIO_COMMAND_EDITOR_MOVE_PREVIOUS_GROUP, "Move Editor to Previous Group", "Move the active tab into the other editor group", "go-previous-symbolic", "Ctrl+Alt+Left", 1, 1, 0, 0, 187, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.focus-next-group", UMI_STUDIO_COMMAND_EDITOR_FOCUS_NEXT_GROUP, "Focus Next Editor Group", "Move keyboard focus to the other editor group", "go-jump-symbolic", "Ctrl+Alt+G", 1, 1, 0, 0, 188, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.balance-groups", UMI_STUDIO_COMMAND_EDITOR_BALANCE_GROUPS, "Balance Editor Groups", "Give both editor groups equal workspace", "view-grid-symbolic", "", 1, 1, 0, 0, 189, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.editor.reset-groups", UMI_STUDIO_COMMAND_EDITOR_RESET_GROUPS, "Reset Editor Groups", "Merge editor groups without closing documents", "view-restore-symbolic", "", 1, 1, 0, 0, 190, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.go.line", UMI_DOCUMENT_COMMAND_GO_TO_LINE, "Go to Line…", "Navigate to a line in the active document", "go-jump-symbolic", "Ctrl+G", 1, 1, 0, 0, 195, "", UMI_UI_ACTION_ARGUMENT_LINE_NUMBER },
    { "studio.action.build.configure", UMI_STUDIO_COMMAND_BUILD_CONFIGURE, "Configure Workspace", "Configure the active CMake build profile", "emblem-system-symbolic", "", 1, 1, 0, 0, 200, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.compile", UMI_STUDIO_COMMAND_BUILD_COMPILE, "Build Workspace", "Compile the active CMake build profile", "system-run-symbolic", "Ctrl+Shift+B", 1, 1, 0, 0, 210, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.test", UMI_STUDIO_COMMAND_BUILD_TEST, "Run Tests", "Run all CTest tests in the active profile", "emblem-ok-symbolic", "Ctrl+Alt+T", 1, 1, 0, 0, 220, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.clean", UMI_STUDIO_COMMAND_BUILD_CLEAN, "Clean Workspace", "Clean generated outputs in the active profile", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 230, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.run", UMI_STUDIO_COMMAND_BUILD_RUN, "Start Without Debugging", "Start the configured Studio executable without a debug adapter", "media-playback-start-symbolic", "Ctrl+F5", 1, 1, 0, 0, 240, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.install", UMI_STUDIO_COMMAND_BUILD_INSTALL, "Deploy Local", "Install into the configured local staging prefix", "package-x-generic-symbolic", "", 1, 1, 0, 0, 250, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.filter", UMI_STUDIO_COMMAND_BUILD_FILTER, "Filter Build Graph…", "Filter nodes by text or lifecycle state", "view-filter-symbolic", "", 1, 1, 0, 0, 251, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.build.select-node", UMI_STUDIO_COMMAND_BUILD_SELECT_NODE, "Select Build Node…", "Select a graph node by stable identifier", "object-select-symbolic", "", 1, 1, 0, 0, 252, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.build.select-operation", UMI_STUDIO_COMMAND_BUILD_SELECT_OPERATION, "Select Build Operation…", "Select retained build evidence by operation ID", "object-select-symbolic", "", 1, 1, 0, 0, 253, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.build.select-artifact", UMI_STUDIO_COMMAND_BUILD_SELECT_ARTIFACT, "Select Build Artifact…", "Select a produced artifact by stable identifier", "object-select-symbolic", "", 1, 1, 0, 0, 254, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.build.run-next", UMI_STUDIO_COMMAND_BUILD_RUN_NEXT, "Run Next Build Node", "Execute the next ready graph node", "media-playback-start-symbolic", "", 1, 1, 0, 0, 255, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.run-all", UMI_STUDIO_COMMAND_BUILD_RUN_ALL, "Run Build Plan", "Execute all ready nodes in dependency order", "system-run-symbolic", "", 1, 1, 0, 0, 256, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.retry", UMI_STUDIO_COMMAND_BUILD_RETRY, "Retry Selected Build Node", "Retry the selected failed graph node", "view-refresh-symbolic", "", 1, 1, 0, 0, 257, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.invalidate", UMI_STUDIO_COMMAND_BUILD_INVALIDATE, "Invalidate Build Node…", "Mark a node pending after its inputs change", "view-refresh-symbolic", "", 1, 1, 0, 0, 258, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.build.refresh", UMI_STUDIO_COMMAND_BUILD_REFRESH, "Refresh Build Workspace", "Refresh graph readiness, selection and totals", "view-refresh-symbolic", "", 1, 1, 0, 0, 259, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.build.clear-history", UMI_STUDIO_COMMAND_BUILD_CLEAR_HISTORY, "Clear Build History", "Clear retained build results and output evidence", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 259, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.build-dashboard", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Build Dashboard", "Show or hide the Build Dashboard", "system-run-symbolic", "", 1, 1, 1, 1, 259, UMI_STUDIO_PANE_BUILD_DASHBOARD, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.build-graph", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Build Graph", "Show or hide the Build Graph", "view-list-tree-symbolic", "", 1, 1, 1, 1, 259, UMI_STUDIO_PANE_BUILD_GRAPH, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.build-history", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Build History", "Show or hide Build History", "document-open-recent-symbolic", "", 1, 1, 1, 1, 259, UMI_STUDIO_PANE_BUILD_HISTORY, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.build-output", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Build Output", "Show or hide Build Output", "utilities-terminal-symbolic", "", 1, 1, 1, 1, 259, UMI_STUDIO_PANE_BUILD_OUTPUT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.build-artifacts", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Build Artifacts", "Show or hide Build Artifacts", "package-x-generic-symbolic", "", 1, 1, 1, 1, 259, UMI_STUDIO_PANE_BUILD_ARTIFACTS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.build-tasks", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Build Tasks", "Show or hide Build Tasks", "view-list-symbolic", "", 1, 1, 1, 1, 259, UMI_STUDIO_PANE_BUILD_TASKS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.discover", UMI_STUDIO_COMMAND_TESTS_DISCOVER, "Discover Tests", "Discover CTest tests in the active build directory", "system-search-symbolic", "", 1, 1, 0, 0, 260, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.filter", UMI_STUDIO_COMMAND_TESTS_FILTER, "Filter Tests…", "Filter tests by text or latest outcome", "edit-find-symbolic", "", 1, 1, 0, 0, 261, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.test.select", UMI_STUDIO_COMMAND_TESTS_SELECT, "Select Test…", "Select a test by stable identifier", "go-jump-symbolic", "", 1, 1, 0, 0, 262, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.test.run-all", UMI_STUDIO_COMMAND_TESTS_RUN_ALL, "Run All Tests", "Run every visible test", "media-playback-start-symbolic", "Ctrl+Alt+T", 1, 1, 0, 0, 263, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.run-selected", UMI_STUDIO_COMMAND_TESTS_RUN_SELECTED, "Run Selected Test", "Run the selected test", "media-playback-start-symbolic", "", 1, 1, 0, 0, 264, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.debug-selected", UMI_STUDIO_COMMAND_TESTS_DEBUG_SELECTED, "Debug Selected Test", "Run the selected test with debugger context", "debug-run-symbolic", "", 1, 1, 0, 0, 265, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.coverage", UMI_STUDIO_COMMAND_TESTS_RUN_COVERAGE, "Run with Coverage", "Run visible tests and collect coverage", "view-statistics-symbolic", "", 1, 1, 0, 0, 266, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.rerun-failed", UMI_STUDIO_COMMAND_TESTS_RERUN_FAILED, "Rerun Failed Tests", "Rerun tests whose latest result failed", "view-refresh-symbolic", "", 1, 1, 0, 0, 267, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.repeat-selected", UMI_STUDIO_COMMAND_TESTS_REPEAT_SELECTED, "Repeat Selected Test…", "Repeat the selected test to diagnose intermittent failures", "view-refresh-symbolic", "", 1, 1, 0, 0, 268, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.test.stop", UMI_STUDIO_COMMAND_TESTS_STOP, "Stop Test Run", "Request cancellation of the active test run", "media-playback-stop-symbolic", "", 1, 1, 0, 0, 269, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.clear-results", UMI_STUDIO_COMMAND_TESTS_CLEAR_RESULTS, "Clear Test Results", "Clear retained result evidence", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 270, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.clear-output", UMI_STUDIO_COMMAND_TESTS_CLEAR_OUTPUT, "Clear Test Output", "Clear retained test output", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 271, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.test.clear-coverage", UMI_STUDIO_COMMAND_TESTS_CLEAR_COVERAGE, "Clear Test Coverage", "Clear retained coverage summaries", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 272, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.testing", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Test Explorer", "Show or hide the Test Explorer", "emblem-ok-symbolic", "", 1, 1, 1, 1, 273, UMI_STUDIO_PANE_TESTING, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.test-results", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Test Results", "Show or hide Test Results", "emblem-ok-symbolic", "", 1, 1, 1, 1, 274, UMI_STUDIO_PANE_TEST_RESULTS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.test-failures", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Test Failures", "Show or hide Test Failures", "dialog-error-symbolic", "", 1, 1, 1, 1, 275, UMI_STUDIO_PANE_TEST_FAILURES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.test-output", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Test Output", "Show or hide Test Output", "utilities-terminal-symbolic", "", 1, 1, 1, 1, 276, UMI_STUDIO_PANE_TEST_OUTPUT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.test-coverage", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Test Coverage", "Show or hide Test Coverage", "view-statistics-symbolic", "", 1, 1, 1, 1, 277, UMI_STUDIO_PANE_TEST_COVERAGE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.test-runs", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Test Runs", "Show or hide Test Runs", "document-open-recent-symbolic", "", 1, 1, 1, 1, 278, UMI_STUDIO_PANE_TEST_RUNS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.show", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Show Terminal", "Show or hide the terminal pane", "utilities-terminal-symbolic", "Ctrl+`", 1, 1, 1, 1, 270, UMI_STUDIO_PANE_TERMINAL, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.execute", UMI_STUDIO_COMMAND_TERMINAL_EXECUTE, "Execute in Terminal…", "Execute a command in the primary terminal", "utilities-terminal-symbolic", "", 1, 1, 0, 0, 280, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.terminal.clear", UMI_STUDIO_COMMAND_TERMINAL_CLEAR, "Clear Terminal", "Clear the primary terminal transcript", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 290, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.new", UMI_STUDIO_COMMAND_TERMINAL_NEW, "New Terminal", "Open a terminal using the default profile", "tab-new-symbolic", "Ctrl+Shift+`", 1, 1, 0, 0, 291, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.close", UMI_STUDIO_COMMAND_TERMINAL_CLOSE, "Close Terminal", "Close the active terminal", "window-close-symbolic", "", 1, 1, 0, 0, 292, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.next", UMI_STUDIO_COMMAND_TERMINAL_NEXT, "Next Terminal", "Activate the next terminal tab", "go-next-symbolic", "", 1, 1, 0, 0, 293, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.previous", UMI_STUDIO_COMMAND_TERMINAL_PREVIOUS, "Previous Terminal", "Activate the previous terminal tab", "go-previous-symbolic", "", 1, 1, 0, 0, 294, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.split", UMI_STUDIO_COMMAND_TERMINAL_SPLIT_HORIZONTAL, "Split Terminal", "Split the active terminal horizontally", "view-split-left-right-symbolic", "", 1, 1, 0, 0, 295, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.split-horizontal", UMI_STUDIO_COMMAND_TERMINAL_SPLIT_HORIZONTAL, "Split Horizontally", "Split the active terminal horizontally", "view-split-left-right-symbolic", "", 1, 1, 0, 0, 296, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.split-vertical", UMI_STUDIO_COMMAND_TERMINAL_SPLIT_VERTICAL, "Split Vertically", "Split the active terminal vertically", "view-split-top-bottom-symbolic", "", 1, 1, 0, 0, 297, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.terminal.search", UMI_STUDIO_COMMAND_TERMINAL_SEARCH, "Search Terminal…", "Search the active terminal transcript", "edit-find-symbolic", "Ctrl+Shift+F", 1, 1, 0, 0, 298, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.terminal.history-clear", UMI_STUDIO_COMMAND_TERMINAL_HISTORY_CLEAR, "Clear Terminal History", "Clear retained command history", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 299, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.processes", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Processes", "Show or hide supervised processes", "system-run-symbolic", "", 1, 1, 1, 1, 300, UMI_STUDIO_PANE_PROCESSES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.tasks", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Tasks", "Show or hide background tasks", "view-list-symbolic", "", 1, 1, 1, 1, 301, UMI_STUDIO_PANE_TASKS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.terminal-history", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Terminal History", "Show or hide terminal command history", "document-open-recent-symbolic", "", 1, 1, 1, 1, 302, UMI_STUDIO_PANE_TERMINAL_HISTORY, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.process.refresh", UMI_STUDIO_COMMAND_PROCESS_REPORT, "Refresh Processes", "Refresh supervised process state", "view-refresh-symbolic", "", 1, 1, 0, 0, 303, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.process.cancel", UMI_STUDIO_COMMAND_PROCESS_CANCEL, "Cancel Process…", "Cancel a supervised process by ID", "process-stop-symbolic", "", 1, 1, 0, 0, 304, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.tasks.refresh", UMI_STUDIO_COMMAND_TASKS_REPORT, "Refresh Tasks", "Refresh shared task queue state", "view-refresh-symbolic", "", 1, 1, 0, 0, 305, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.tasks.wait", UMI_STUDIO_COMMAND_TASKS_WAIT_IDLE, "Wait for Tasks", "Wait for queued tasks to become idle", "media-playback-pause-symbolic", "", 1, 1, 0, 0, 306, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.tasks.retry", UMI_STUDIO_COMMAND_BUILD_RETRY, "Retry Operation…", "Retry a failed build operation node", "view-refresh-symbolic", "", 1, 1, 0, 0, 307, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.tasks.cancel", UMI_STUDIO_COMMAND_BUILD_CANCEL, "Cancel Build", "Cancel the active build operation", "process-stop-symbolic", "", 1, 1, 0, 0, 308, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.problems.clear", UMI_STUDIO_COMMAND_DIAGNOSTICS_CLEAR, "Clear Problems", "Clear retained compiler, language and runtime problems", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 292, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.output.clear", UMI_STUDIO_COMMAND_OUTPUT_CLEAR, "Clear Output", "Clear retained build, terminal and runtime output", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 294, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.language.initialize", UMI_STUDIO_COMMAND_LANGUAGE_INITIALIZE, "Start Language Intelligence", "Initialise the active Language Server Protocol client", "accessories-dictionary-symbolic", "", 1, 1, 0, 0, 300, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.language.workspace-symbols", UMI_STUDIO_COMMAND_LANGUAGE_WORKSPACE_SYMBOLS, "Go to Symbol in Workspace…", "Search workspace symbols through the active language server", "system-search-symbolic", "Ctrl+T", 1, 1, 0, 0, 310, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.start", UMI_STUDIO_COMMAND_DEBUG_START, "Start Debugging", "Launch the configured program through the active debug adapter", "debug-run-symbolic", "F5", 1, 1, 0, 0, 320, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.continue", UMI_STUDIO_COMMAND_DEBUG_CONTINUE, "Continue", "Continue the selected debug thread", "media-playback-start-symbolic", "F6", 1, 1, 0, 0, 330, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.pause", UMI_STUDIO_COMMAND_DEBUG_PAUSE, "Pause", "Pause the selected debug thread", "media-playback-pause-symbolic", "", 1, 1, 0, 0, 340, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.next", UMI_STUDIO_COMMAND_DEBUG_NEXT, "Step Over", "Step over the next statement", "go-next-symbolic", "F10", 1, 1, 0, 0, 350, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.step-in", UMI_STUDIO_COMMAND_DEBUG_STEP_IN, "Step Into", "Step into the next function call", "go-down-symbolic", "F11", 1, 1, 0, 0, 360, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.step-out", UMI_STUDIO_COMMAND_DEBUG_STEP_OUT, "Step Out", "Step out of the current function", "go-up-symbolic", "Shift+F11", 1, 1, 0, 0, 370, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.stop", UMI_STUDIO_COMMAND_DEBUG_STOP, "Stop Debugging", "Terminate the active debug session", "media-playback-stop-symbolic", "Shift+F5", 1, 1, 0, 0, 380, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.debug.add-breakpoint", UMI_STUDIO_COMMAND_DEBUG_ADD_BREAKPOINT, "Add Breakpoint…", "Add a Framework-owned source breakpoint using path:line", "media-record-symbolic", "F9", 1, 1, 0, 0, 390, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.toggle-breakpoint", UMI_STUDIO_COMMAND_DEBUG_SET_BREAKPOINT_ENABLED, "Enable or Disable Breakpoint…", "Set breakpoint state using id=1 or id=0", "object-select-symbolic", "", 1, 1, 0, 0, 391, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.remove-breakpoint", UMI_STUDIO_COMMAND_DEBUG_REMOVE_BREAKPOINT, "Remove Breakpoint…", "Remove a breakpoint by its stable ID", "list-remove-symbolic", "", 1, 1, 0, 0, 392, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.add-watch", UMI_STUDIO_COMMAND_DEBUG_ADD_WATCH, "Add Watch…", "Add an expression to the Watch pane", "list-add-symbolic", "", 1, 1, 0, 0, 393, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.remove-watch", UMI_STUDIO_COMMAND_DEBUG_REMOVE_WATCH, "Remove Watch…", "Remove a watch by its stable ID", "list-remove-symbolic", "", 1, 1, 0, 0, 394, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.select-thread", UMI_STUDIO_COMMAND_DEBUG_SELECT_THREAD, "Select Debug Thread…", "Select a thread by its stable ID", "go-jump-symbolic", "", 1, 1, 0, 0, 395, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.select-frame", UMI_STUDIO_COMMAND_DEBUG_SELECT_FRAME, "Select Stack Frame…", "Select a stack frame by its stable ID", "go-jump-symbolic", "", 1, 1, 0, 0, 396, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.select-scope", UMI_STUDIO_COMMAND_DEBUG_SELECT_SCOPE, "Select Variable Scope…", "Select a variable scope by its stable ID", "go-jump-symbolic", "", 1, 1, 0, 0, 397, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.debug.clear-console", UMI_STUDIO_COMMAND_DEBUG_CLEAR_CONSOLE, "Clear Debug Console", "Clear retained Debug Console entries", "edit-clear-all-symbolic", "", 1, 1, 0, 0, 398, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.debug-call-stack", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Call Stack", "Show or hide the Call Stack pane", "view-list-tree-symbolic", "", 1, 1, 1, 1, 399, UMI_STUDIO_PANE_DEBUG_CALL_STACK, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.debug-variables", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Variables", "Show or hide the Variables pane", "view-list-symbolic", "", 1, 1, 1, 1, 399, UMI_STUDIO_PANE_DEBUG_VARIABLES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.debug-watches", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Watch", "Show or hide the Watch pane", "system-search-symbolic", "", 1, 1, 1, 1, 399, UMI_STUDIO_PANE_DEBUG_WATCHES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.debug-breakpoints", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Breakpoints", "Show or hide the Breakpoints pane", "media-record-symbolic", "", 1, 1, 1, 1, 399, UMI_STUDIO_PANE_DEBUG_BREAKPOINTS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.debug-console", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Debug Console", "Show or hide the Debug Console", "utilities-terminal-symbolic", "", 1, 1, 1, 1, 399, UMI_STUDIO_PANE_DEBUG_CONSOLE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.refresh", UMI_STUDIO_COMMAND_VCS_REFRESH, "Refresh Source Control", "Refresh working tree, history, branches, remotes and tags", "view-refresh-symbolic", "Ctrl+Shift+G", 1, 1, 0, 0, 400, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.stage", UMI_STUDIO_COMMAND_VCS_STAGE, "Stage Path…", "Stage a repository-relative path", "list-add-symbolic", "", 1, 1, 0, 0, 410, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.unstage", UMI_STUDIO_COMMAND_VCS_UNSTAGE, "Unstage Path…", "Remove a path from the index", "list-remove-symbolic", "", 1, 1, 0, 0, 420, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.stage-all", UMI_STUDIO_COMMAND_VCS_STAGE_ALL, "Stage All", "Stage every working-tree change", "list-add-symbolic", "", 1, 1, 0, 0, 430, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.unstage-all", UMI_STUDIO_COMMAND_VCS_UNSTAGE_ALL, "Unstage All", "Remove every indexed change", "list-remove-symbolic", "", 1, 1, 0, 0, 440, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.discard", UMI_STUDIO_COMMAND_VCS_DISCARD, "Discard Path…", "Discard a working-tree path", "edit-delete-symbolic", "", 1, 1, 0, 0, 450, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.commit", UMI_STUDIO_COMMAND_VCS_COMMIT, "Commit…", "Create a commit from indexed changes", "document-save-symbolic", "Ctrl+Enter", 1, 1, 0, 0, 460, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.fetch", UMI_STUDIO_COMMAND_VCS_FETCH, "Fetch", "Fetch all remotes and prune stale refs", "folder-download-symbolic", "", 1, 1, 0, 0, 470, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.pull", UMI_STUDIO_COMMAND_VCS_PULL, "Pull", "Fast-forward the active branch", "go-down-symbolic", "", 1, 1, 0, 0, 480, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.push", UMI_STUDIO_COMMAND_VCS_PUSH, "Push", "Push the active branch", "go-up-symbolic", "", 1, 1, 0, 0, 490, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.branch-create", UMI_STUDIO_COMMAND_VCS_BRANCH_CREATE, "New Branch…", "Create and check out a branch", "list-add-symbolic", "", 1, 1, 0, 0, 500, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.branch-checkout", UMI_STUDIO_COMMAND_VCS_BRANCH_CHECKOUT, "Checkout Branch…", "Switch to an existing branch", "go-jump-symbolic", "", 1, 1, 0, 0, 510, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.branch-delete", UMI_STUDIO_COMMAND_VCS_BRANCH_DELETE, "Delete Branch…", "Safely delete a merged branch", "edit-delete-symbolic", "", 1, 1, 0, 0, 520, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.diff", UMI_STUDIO_COMMAND_VCS_DIFF, "Open Diff…", "Open a working-tree or staged path diff", "document-properties-symbolic", "", 1, 1, 0, 0, 530, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.filter", UMI_STUDIO_COMMAND_VCS_FILTER, "Filter Changes…", "Show all, staged, unstaged or conflicting changes", "view-filter-symbolic", "", 1, 1, 0, 0, 531, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.select-change", UMI_STUDIO_COMMAND_VCS_SELECT_CHANGE, "Select Change…", "Select a repository-relative path", "object-select-symbolic", "", 1, 1, 0, 0, 532, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.select-commit", UMI_STUDIO_COMMAND_VCS_SELECT_COMMIT, "Select Commit…", "Select a commit by identifier", "object-select-symbolic", "", 1, 1, 0, 0, 533, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.select-branch", UMI_STUDIO_COMMAND_VCS_SELECT_BRANCH, "Select Branch…", "Select a branch without checking it out", "object-select-symbolic", "", 1, 1, 0, 0, 534, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.select-remote", UMI_STUDIO_COMMAND_VCS_SELECT_REMOTE, "Select Remote…", "Select a configured remote", "object-select-symbolic", "", 1, 1, 0, 0, 535, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.set-commit-message", UMI_STUDIO_COMMAND_VCS_SET_COMMIT_MESSAGE, "Commit Message…", "Compose the commit message", "insert-text-symbolic", "", 1, 1, 0, 0, 536, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.vcs.stage-selected", UMI_STUDIO_COMMAND_VCS_STAGE_SELECTED, "Stage Selected", "Stage the selected path", "list-add-symbolic", "", 1, 1, 0, 0, 537, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.unstage-selected", UMI_STUDIO_COMMAND_VCS_UNSTAGE_SELECTED, "Unstage Selected", "Remove the selected path from the index", "list-remove-symbolic", "", 1, 1, 0, 0, 538, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.discard-selected", UMI_STUDIO_COMMAND_VCS_DISCARD_SELECTED, "Discard Selected…", "Discard the selected unstaged path", "edit-delete-symbolic", "", 1, 1, 0, 0, 539, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.commit-composed", UMI_STUDIO_COMMAND_VCS_COMMIT_COMPOSED, "Commit Composed Changes", "Commit staged changes using the composed message", "document-save-symbolic", "Ctrl+Enter", 1, 1, 0, 0, 540, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.diff-selected", UMI_STUDIO_COMMAND_VCS_DIFF_SELECTED, "Open Selected Diff", "Open the selected working-tree diff", "document-properties-symbolic", "", 1, 1, 0, 0, 541, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.vcs.diff-selected-staged", UMI_STUDIO_COMMAND_VCS_DIFF_SELECTED_STAGED, "Open Selected Staged Diff", "Open the selected index diff", "document-properties-symbolic", "", 1, 1, 0, 0, 542, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.extensions.refresh", UMI_STUDIO_COMMAND_PLUGINS_REPORT, "Refresh Extensions", "Refresh and report installed extension state", "view-refresh-symbolic", "", 1, 1, 0, 0, 540, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.extension-catalogue", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Extension Catalogue", "Show or hide the Extension Catalogue", "system-search-symbolic", "", 1, 1, 1, 1, 550, UMI_STUDIO_PANE_EXTENSION_CATALOGUE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.extension-permissions", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Extension Permissions", "Show or hide extension permissions", "security-high-symbolic", "", 1, 1, 1, 1, 560, UMI_STUDIO_PANE_EXTENSION_PERMISSIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.extension-audit", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Extension Audit", "Show or hide extension audit history", "document-open-recent-symbolic", "", 1, 1, 1, 1, 570, UMI_STUDIO_PANE_EXTENSION_AUDIT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-commit", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Commit", "Show commit composition", "document-save-symbolic", "", 1, 1, 1, 1, 543, UMI_STUDIO_PANE_VCS_COMMIT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-history", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Repository History", "Show repository history", "document-open-recent-symbolic", "", 1, 1, 1, 1, 544, UMI_STUDIO_PANE_VCS_HISTORY, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-branches", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Branches", "Show repository branches", "view-list-tree-symbolic", "", 1, 1, 1, 1, 545, UMI_STUDIO_PANE_VCS_BRANCHES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-remotes", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Remotes", "Show repository remotes", "network-server-symbolic", "", 1, 1, 1, 1, 546, UMI_STUDIO_PANE_VCS_REMOTES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-conflicts", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Merge Conflicts", "Show unresolved merge conflicts", "dialog-warning-symbolic", "", 1, 1, 1, 1, 547, UMI_STUDIO_PANE_VCS_CONFLICTS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-diff", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Diff Viewer", "Show source-control diff viewer", "document-properties-symbolic", "", 1, 1, 1, 1, 548, UMI_STUDIO_PANE_VCS_DIFF, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.vcs-operations", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Source Control Operations", "Show repository operation history", "view-history-symbolic", "", 1, 1, 1, 1, 549, UMI_STUDIO_PANE_VCS_OPERATIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.ai.refresh-health", UMI_STUDIO_COMMAND_AI_REFRESH_HEALTH, "Refresh AI Health", "Probe AI providers and AuthorEngine runtimes", "view-refresh-symbolic", "", 1, 1, 0, 0, 572, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.ai.new-session", UMI_STUDIO_COMMAND_AI_NEW_SESSION, "New AI Session…", "Create a governed AuthorEngine conversation session", "document-new-symbolic", "", 1, 1, 0, 0, 574, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.save-session", UMI_STUDIO_COMMAND_AI_SAVE_SESSION, "Save AI Session…", "Persist the active AI session when privacy policy permits", "document-save-symbolic", "", 1, 1, 0, 0, 576, "", UMI_UI_ACTION_ARGUMENT_SAVE_PATH },
    { "studio.action.pane.ai-workspace", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Workspace", "Open the AuthorEngine integration overview", "mail-message-new-symbolic", "", 1, 1, 1, 1, 578, UMI_STUDIO_PANE_AI, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.ai-runtimes", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Runtimes", "Inspect provider and model runtimes", "computer-symbolic", "", 1, 1, 1, 1, 580, UMI_STUDIO_PANE_AI_RUNTIMES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.ai-context", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Context", "Inspect context sources and token budgets", "folder-documents-symbolic", "", 1, 1, 1, 1, 582, UMI_STUDIO_PANE_AI_CONTEXT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.ai-sessions", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Sessions", "Inspect conversation session state", "document-open-recent-symbolic", "", 1, 1, 1, 1, 584, UMI_STUDIO_PANE_AI_SESSIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.ai-privacy", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Privacy", "Inspect remote sharing, approval and persistence controls", "security-high-symbolic", "", 1, 1, 1, 1, 586, UMI_STUDIO_PANE_AI_PRIVACY, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.ai.code-chat", UMI_STUDIO_COMMAND_AI_CODE_CHAT, "Code Chat…", "Discuss the active code with governed repository context", "mail-message-new-symbolic", "Ctrl+Alt+A", 1, 1, 0, 0, 588, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.complete-code", UMI_STUDIO_COMMAND_AI_COMPLETE_CODE, "Complete Code…", "Plan context-aware completion", "insert-text-symbolic", "", 1, 1, 0, 0, 590, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.explain-code", UMI_STUDIO_COMMAND_AI_EXPLAIN_CODE, "Explain Code…", "Explain code with repository context", "dialog-information-symbolic", "", 1, 1, 0, 0, 592, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.refactor-code", UMI_STUDIO_COMMAND_AI_REFACTOR_CODE, "Refactor Code…", "Prepare a reviewable refactoring patch", "applications-development-symbolic", "", 1, 1, 0, 0, 594, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.generate-tests", UMI_STUDIO_COMMAND_AI_GENERATE_TESTS, "Generate Tests…", "Prepare reviewable repository-aware tests", "emblem-ok-symbolic", "", 1, 1, 0, 0, 596, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.patch-approve", UMI_STUDIO_COMMAND_AI_PATCH_APPROVE, "Approve AI Patch…", "Approve the exact current patch preview", "emblem-ok-symbolic", "", 1, 1, 0, 0, 598, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.patch-apply", UMI_STUDIO_COMMAND_AI_PATCH_APPLY, "Apply AI Patch…", "Apply an approved conflict-free patch", "document-save-symbolic", "", 1, 1, 0, 0, 600, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.ai.patch-revert", UMI_STUDIO_COMMAND_AI_PATCH_REVERT, "Revert AI Patch…", "Revert an unchanged applied patch", "edit-undo-symbolic", "", 1, 1, 0, 0, 602, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.pane.ai-coding", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Assistant and Vibe Coding", "Describe a goal and follow its context, review and validation workflow", "applications-development-symbolic", "", 1, 1, 1, 1, 604, UMI_STUDIO_PANE_AI_CODING, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.ai-coding-context", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Coding Context", "Inspect repository prompt context", "folder-documents-symbolic", "", 1, 1, 1, 1, 606, UMI_STUDIO_PANE_AI_CODING_CONTEXT, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.ai-patch-review", UMI_STUDIO_COMMAND_PANE_TOGGLE, "AI Patch Review", "Inspect and control the latest coding patch", "document-properties-symbolic", "", 1, 1, 1, 1, 608, UMI_STUDIO_PANE_AI_PATCH_REVIEW, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.knowledge.collection-create", UMI_STUDIO_COMMAND_KNOWLEDGE_COLLECTION_CREATE, "New Knowledge Collection…", "Create an isolated knowledge collection", "document-new-symbolic", "", 1, 1, 0, 0, 610, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.knowledge.ingest", UMI_STUDIO_COMMAND_KNOWLEDGE_INGEST, "Add Knowledge Source…", "Ingest text with source provenance", "document-open-symbolic", "", 1, 1, 0, 0, 612, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.knowledge.refresh", UMI_STUDIO_COMMAND_KNOWLEDGE_REFRESH, "Refresh Knowledge", "Refresh changed knowledge sources", "view-refresh-symbolic", "", 1, 1, 0, 0, 614, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.knowledge.search", UMI_STUDIO_COMMAND_KNOWLEDGE_SEARCH, "Search Knowledge…", "Search indexed project, code and document evidence", "system-search-symbolic", "Ctrl+Alt+K", 1, 1, 0, 0, 616, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.pane.knowledge", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Knowledge Centre", "Open the Native RAG overview", "folder-documents-symbolic", "", 1, 1, 1, 1, 618, UMI_STUDIO_PANE_KNOWLEDGE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.knowledge-collections", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Knowledge Collections", "Inspect retrieval collections", "view-list-tree-symbolic", "", 1, 1, 1, 1, 620, UMI_STUDIO_PANE_KNOWLEDGE_COLLECTIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.knowledge-sources", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Knowledge Sources", "Inspect indexed sources", "folder-symbolic", "", 1, 1, 1, 1, 622, UMI_STUDIO_PANE_KNOWLEDGE_SOURCES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.knowledge-search", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Knowledge Search", "Open cited search results", "system-search-symbolic", "", 1, 1, 1, 1, 624, UMI_STUDIO_PANE_KNOWLEDGE_SEARCH, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.knowledge-source", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Knowledge Source Viewer", "Open the exact cited source range", "text-x-generic-symbolic", "", 1, 1, 1, 1, 626, UMI_STUDIO_PANE_KNOWLEDGE_SOURCE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.marketplace.check-updates", UMI_STUDIO_COMMAND_MARKETPLACE_CHECK_UPDATES, "Check for Product Updates", "Evaluate installed products against verified releases", "view-refresh-symbolic", "", 1, 1, 0, 0, 580, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.marketplace.plan-update", UMI_STUDIO_COMMAND_MARKETPLACE_PLAN_UPDATE, "Plan Product Update…", "Create a recoverable update plan for a release ID", "system-software-install-symbolic", "", 1, 1, 0, 0, 590, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.pane.product-marketplace", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Product Marketplace", "Browse verified application, runtime and template releases", "system-software-install-symbolic", "", 1, 1, 1, 1, 600, UMI_STUDIO_PANE_PRODUCT_MARKETPLACE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.products-installed", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Installed Products", "Inspect installed versions and rollback readiness", "package-x-generic-symbolic", "", 1, 1, 1, 1, 610, UMI_STUDIO_PANE_PRODUCTS_INSTALLED, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.product-updates", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Product Updates", "Inspect verified update notifications", "software-update-available-symbolic", "", 1, 1, 1, 1, 620, UMI_STUDIO_PANE_PRODUCT_UPDATES, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.product-transactions", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Distribution Transactions", "Inspect install, update and rollback plans", "document-open-recent-symbolic", "", 1, 1, 1, 1, 630, UMI_STUDIO_PANE_PRODUCT_TRANSACTIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.product-evidence", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Supply-chain Evidence", "Inspect checksum, signature, SBOM, licence and provenance evidence", "security-high-symbolic", "", 1, 1, 1, 1, 640, UMI_STUDIO_PANE_PRODUCT_EVIDENCE, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.trading.refresh", UMI_STUDIO_COMMAND_TRADING_REFRESH, "Refresh Trading Workspace", "Refresh derived market, order and portfolio state", "view-refresh-symbolic", "", 1, 1, 0, 0, 650, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.trading.filter-instruments", UMI_STUDIO_COMMAND_TRADING_FILTER_INSTRUMENTS, "Filter Instruments…", "Filter by symbol, venue, currency or identifier", "view-filter-symbolic", "", 1, 1, 0, 0, 651, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.select-instrument", UMI_STUDIO_COMMAND_TRADING_SELECT_INSTRUMENT, "Select Instrument…", "Select the instrument used across trading panes", "object-select-symbolic", "", 1, 1, 0, 0, 652, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.set-environment", UMI_STUDIO_COMMAND_TRADING_SET_ENVIRONMENT, "Set Environment…", "Choose simulation, paper or live with safety gates", "security-high-symbolic", "", 1, 1, 0, 0, 653, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.set-side", UMI_STUDIO_COMMAND_TRADING_SET_SIDE, "Set Side…", "Set the draft order to buy or sell", "go-jump-symbolic", "", 1, 1, 0, 0, 654, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.set-type", UMI_STUDIO_COMMAND_TRADING_SET_TYPE, "Set Type / TIF…", "Set order type and time in force", "document-edit-symbolic", "", 1, 1, 0, 0, 655, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.set-quantity", UMI_STUDIO_COMMAND_TRADING_SET_QUANTITY, "Set Quantity…", "Set a positive draft order quantity", "document-edit-symbolic", "", 1, 1, 0, 0, 656, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.set-prices", UMI_STUDIO_COMMAND_TRADING_SET_PRICES, "Set Prices…", "Set limit and optional stop prices", "document-edit-symbolic", "", 1, 1, 0, 0, 657, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.preview-order", UMI_STUDIO_COMMAND_TRADING_PREVIEW_ORDER, "Preview Order Risk", "Evaluate pre-trade risk without submitting", "dialog-information-symbolic", "", 1, 1, 0, 0, 658, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.trading.submit-order", UMI_STUDIO_COMMAND_TRADING_SUBMIT_ORDER, "Submit Draft Order", "Submit only when every trading safety gate permits", "media-playback-start-symbolic", "", 1, 1, 0, 0, 659, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.trading.filter-orders", UMI_STUDIO_COMMAND_TRADING_FILTER_ORDERS, "Filter Orders…", "Show all, open, filled, cancelled or rejected orders", "view-filter-symbolic", "", 1, 1, 0, 0, 660, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.select-order", UMI_STUDIO_COMMAND_TRADING_SELECT_ORDER, "Select Order…", "Select an order by client order identifier", "object-select-symbolic", "", 1, 1, 0, 0, 661, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.cancel-order", UMI_STUDIO_COMMAND_TRADING_CANCEL_ORDER, "Cancel Selected Order", "Cancel the selected non-terminal order", "media-playback-stop-symbolic", "", 1, 1, 0, 0, 662, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.trading.engage-kill-switch", UMI_STUDIO_COMMAND_TRADING_ENGAGE_KILL_SWITCH, "Stop Trading…", "Engage the kill switch and retain an operator reason", "process-stop-symbolic", "", 1, 1, 0, 0, 663, "", UMI_UI_ACTION_ARGUMENT_TEXT },
    { "studio.action.trading.reset-kill-switch", UMI_STUDIO_COMMAND_TRADING_RESET_KILL_SWITCH, "Reset Trading Stop", "Reset the kill switch after reviewing its cause", "view-refresh-symbolic", "", 1, 1, 0, 0, 664, "", UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-dashboard", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Trading Dashboard", "Show or hide the Trading Dashboard", "view-statistics-symbolic", "", 1, 1, 1, 1, 670, UMI_STUDIO_PANE_TRADING_DASHBOARD, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-watchlist", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Watchlist", "Show or hide the trading Watchlist", "view-list-symbolic", "", 1, 1, 1, 1, 671, UMI_STUDIO_PANE_TRADING_WATCHLIST, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-depth", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Market Depth", "Show or hide Market Depth", "view-list-tree-symbolic", "", 1, 1, 1, 1, 672, UMI_STUDIO_PANE_TRADING_DEPTH, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-chart", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Chart Analytics", "Show or hide Chart Analytics", "view-statistics-symbolic", "", 1, 1, 1, 1, 673, UMI_STUDIO_PANE_TRADING_CHART, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-order-ticket", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Order Ticket", "Show or hide the Order Ticket", "document-edit-symbolic", "", 1, 1, 1, 1, 674, UMI_STUDIO_PANE_TRADING_ORDER_TICKET, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-orders", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Orders", "Show or hide trading Orders", "view-list-symbolic", "", 1, 1, 1, 1, 675, UMI_STUDIO_PANE_TRADING_ORDERS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-executions", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Executions", "Show or hide trading Executions", "emblem-ok-symbolic", "", 1, 1, 1, 1, 676, UMI_STUDIO_PANE_TRADING_EXECUTIONS, UMI_UI_ACTION_ARGUMENT_NONE },
    { "studio.action.pane.trading-portfolio-risk", UMI_STUDIO_COMMAND_PANE_TOGGLE, "Portfolio & Risk", "Show or hide Portfolio and Risk", "security-high-symbolic", "", 1, 1, 1, 1, 677, UMI_STUDIO_PANE_TRADING_PORTFOLIO_RISK, UMI_UI_ACTION_ARGUMENT_NONE }
};

static const UmiUiMenuSnapshot STUDIO_MENUS[] = {
    { "menu.file.new", "file", "documents", "studio.action.file.new", "", 0, 10 },
    { "menu.file.open", "file", "documents", "studio.action.file.open", "", 0, 20 },
    { "menu.file.sep", "file", "save", "", "", 1, 30 },
    { "menu.file.save", "file", "save", "studio.action.file.save", "", 0, 40 },
    { "menu.file.save-as", "file", "save", "studio.action.file.save-as", "", 0, 50 },
    { "menu.file.close", "file", "documents", "studio.action.file.close", "", 0, 60 },
    { "menu.file.close-others", "file", "documents", "studio.action.editor.close-others", "", 0, 70 },
    { "menu.file.close-all", "file", "documents", "studio.action.editor.close-all", "", 0, 80 },
    { "menu.edit.undo", "edit", "history", "studio.action.edit.undo", "", 0, 10 },
    { "menu.edit.redo", "edit", "history", "studio.action.edit.redo", "", 0, 20 },
    { "menu.edit.sep", "edit", "search", "", "", 1, 30 },
    { "menu.edit.find", "edit", "search", "studio.action.edit.find", "", 0, 40 },
    { "menu.edit.replace", "edit", "search", "studio.action.edit.replace", "", 0, 50 },
    { "menu.view.palette", "view", "commands", "studio.action.view.command-palette", "", 0, 10 },
    { "menu.view.word-wrap", "view", "editor", "studio.action.editor.word-wrap", "", 0, 15 },
    { "menu.view.explorer", "view", "panes", "studio.action.pane.explorer", "", 0, 20 },
    { "menu.view.output", "view", "panes", "studio.action.pane.output", "", 0, 30 },
    { "menu.view.problems", "view", "panes", "studio.action.pane.problems", "", 0, 40 },
    { "menu.view.processes", "view", "panes", "studio.action.pane.processes", "", 0, 42 },
    { "menu.view.tasks", "view", "panes", "studio.action.pane.tasks", "", 0, 44 },
    { "menu.view.terminal-history", "view", "panes", "studio.action.pane.terminal-history", "", 0, 46 },
    { "menu.view.clear-output", "view", "diagnostics", "studio.action.output.clear", "", 0, 50 },
    { "menu.view.clear-problems", "view", "diagnostics", "studio.action.problems.clear", "", 0, 60 },
    { "menu.view.reset", "view", "layout", "studio.action.layout.reset", "", 0, 70 },
    { "menu.window.develop", "window", "workspace-profiles", "studio.action.workspace-profile.develop", "", 0, 10 },
    { "menu.window.focus", "window", "workspace-profiles", "studio.action.workspace-profile.focus", "", 0, 20 },
    { "menu.window.debug", "window", "workspace-profiles", "studio.action.workspace-profile.debug", "", 0, 30 },
    { "menu.window.source-control", "window", "workspace-profiles", "studio.action.workspace-profile.source-control", "", 0, 40 },
    { "menu.window.testing", "window", "workspace-profiles", "studio.action.workspace-profile.testing", "", 0, 45 },
    { "menu.window.build-workspace", "window", "workspace-profiles", "studio.action.workspace-profile.build", "", 0, 47 },
    { "menu.window.review", "window", "workspace-profiles", "studio.action.workspace-profile.review", "", 0, 50 },
    { "menu.window.operations", "window", "workspace-profiles", "studio.action.workspace-profile.operations", "", 0, 60 },
    { "menu.window.trading", "window", "workspace-profiles", "studio.action.workspace-profile.trading", "", 0, 70 },
    { "menu.window.separator", "window", "workspace-profiles", "", "", 1, 80 },
    { "menu.window.reset", "window", "workspace-profiles", "studio.action.layout.reset", "", 0, 90 },
    { "menu.window.pin-editor", "window", "editors", "studio.action.editor.pin-toggle", "", 0, 90 },
    { "menu.window.keep-preview", "window", "editors", "studio.action.editor.keep-preview", "", 0, 100 },
    { "menu.window.editor-separator", "window", "editor-groups", "", "", 1, 110 },
    { "menu.window.split-right", "window", "editor-groups", "studio.action.editor.split-right", "", 0, 120 },
    { "menu.window.split-down", "window", "editor-groups", "studio.action.editor.split-down", "", 0, 130 },
    { "menu.window.move-next-group", "window", "editor-groups", "studio.action.editor.move-next-group", "", 0, 140 },
    { "menu.window.move-previous-group", "window", "editor-groups", "studio.action.editor.move-previous-group", "", 0, 150 },
    { "menu.window.focus-next-group", "window", "editor-groups", "studio.action.editor.focus-next-group", "", 0, 160 },
    { "menu.window.balance-groups", "window", "editor-groups", "studio.action.editor.balance-groups", "", 0, 170 },
    { "menu.window.reset-groups", "window", "editor-groups", "studio.action.editor.reset-groups", "", 0, 180 },
    { "menu.go.line", "go", "navigation", "studio.action.go.line", "", 0, 10 },
    { "menu.go.workspace-symbols", "go", "navigation", "studio.action.language.workspace-symbols", "", 0, 20 },
    { "menu.go.next-editor", "go", "editors", "studio.action.editor.next", "", 0, 30 },
    { "menu.go.previous-editor", "go", "editors", "studio.action.editor.previous", "", 0, 40 },
    { "menu.run.configure", "run", "build", "studio.action.build.configure", "", 0, 10 },
    { "menu.run.build", "run", "build", "studio.action.build.compile", "", 0, 20 },
    { "menu.run.test", "run", "test", "studio.action.build.test", "", 0, 30 },
    { "menu.run.clean", "run", "build", "studio.action.build.clean", "", 0, 40 },
    { "menu.run.start", "run", "run", "studio.action.build.run", "", 0, 50 },
    { "menu.run.deploy", "run", "deploy", "studio.action.build.install", "", 0, 60 },
    { "menu.run.build-filter", "run", "build-workspace", "studio.action.build.filter", "", 0, 61 },
    { "menu.run.build-next", "run", "build-workspace", "studio.action.build.run-next", "", 0, 62 },
    { "menu.run.build-plan", "run", "build-workspace", "studio.action.build.run-all", "", 0, 63 },
    { "menu.run.build-retry", "run", "build-workspace", "studio.action.build.retry", "", 0, 64 },
    { "menu.run.build-refresh", "run", "build-workspace", "studio.action.build.refresh", "", 0, 65 },
    { "menu.run.build-clear-history", "run", "build-workspace", "studio.action.build.clear-history", "", 0, 66 },
    { "menu.run.build-dashboard", "run", "build-views", "studio.action.pane.build-dashboard", "", 0, 67 },
    { "menu.run.build-graph", "run", "build-views", "studio.action.pane.build-graph", "", 0, 68 },
    { "menu.run.build-history", "run", "build-views", "studio.action.pane.build-history", "", 0, 69 },
    { "menu.run.build-output", "run", "build-views", "studio.action.pane.build-output", "", 0, 70 },
    { "menu.run.build-artifacts", "run", "build-views", "studio.action.pane.build-artifacts", "", 0, 71 },
    { "menu.run.build-tasks", "run", "build-views", "studio.action.pane.build-tasks", "", 0, 72 },
    { "menu.run.debug-separator", "run", "debug", "", "", 1, 70 },
    { "menu.run.debug-start", "run", "debug", "studio.action.debug.start", "", 0, 80 },
    { "menu.run.debug-continue", "run", "debug", "studio.action.debug.continue", "", 0, 90 },
    { "menu.run.debug-pause", "run", "debug", "studio.action.debug.pause", "", 0, 100 },
    { "menu.run.debug-next", "run", "debug", "studio.action.debug.next", "", 0, 110 },
    { "menu.run.debug-step-in", "run", "debug", "studio.action.debug.step-in", "", 0, 120 },
    { "menu.run.debug-step-out", "run", "debug", "studio.action.debug.step-out", "", 0, 130 },
    { "menu.run.debug-stop", "run", "debug", "studio.action.debug.stop", "", 0, 140 },
    { "menu.run.debug-breakpoint", "run", "debug", "studio.action.debug.add-breakpoint", "", 0, 150 },
    { "menu.run.debug-watch", "run", "debug-data", "studio.action.debug.add-watch", "", 0, 160 },
    { "menu.run.debug-clear-console", "run", "debug-data", "studio.action.debug.clear-console", "", 0, 170 },
    { "menu.run.debug-call-stack", "run", "debug-views", "studio.action.pane.debug-call-stack", "", 0, 180 },
    { "menu.run.debug-variables", "run", "debug-views", "studio.action.pane.debug-variables", "", 0, 190 },
    { "menu.run.debug-watches", "run", "debug-views", "studio.action.pane.debug-watches", "", 0, 200 },
    { "menu.run.debug-breakpoints", "run", "debug-views", "studio.action.pane.debug-breakpoints", "", 0, 210 },
    { "menu.run.debug-console", "run", "debug-views", "studio.action.pane.debug-console", "", 0, 220 },
    { "menu.test.discover", "test", "discovery", "studio.action.test.discover", "", 0, 10 },
    { "menu.test.filter", "test", "discovery", "studio.action.test.filter", "", 0, 20 },
    { "menu.test.run-all", "test", "execution", "studio.action.test.run-all", "", 0, 30 },
    { "menu.test.run-selected", "test", "execution", "studio.action.test.run-selected", "", 0, 40 },
    { "menu.test.debug-selected", "test", "execution", "studio.action.test.debug-selected", "", 0, 50 },
    { "menu.test.coverage", "test", "execution", "studio.action.test.coverage", "", 0, 60 },
    { "menu.test.rerun-failed", "test", "execution", "studio.action.test.rerun-failed", "", 0, 70 },
    { "menu.test.repeat-selected", "test", "execution", "studio.action.test.repeat-selected", "", 0, 80 },
    { "menu.test.stop", "test", "execution", "studio.action.test.stop", "", 0, 90 },
    { "menu.test.explorer", "test", "views", "studio.action.pane.testing", "", 0, 100 },
    { "menu.test.results", "test", "views", "studio.action.pane.test-results", "", 0, 110 },
    { "menu.test.failures", "test", "views", "studio.action.pane.test-failures", "", 0, 120 },
    { "menu.test.output", "test", "views", "studio.action.pane.test-output", "", 0, 130 },
    { "menu.test.coverage-view", "test", "views", "studio.action.pane.test-coverage", "", 0, 140 },
    { "menu.test.runs", "test", "views", "studio.action.pane.test-runs", "", 0, 150 },
    { "menu.terminal.show", "terminal", "terminal", "studio.action.terminal.show", "", 0, 10 },
    { "menu.terminal.new", "terminal", "sessions", "studio.action.terminal.new", "", 0, 20 },
    { "menu.terminal.close", "terminal", "sessions", "studio.action.terminal.close", "", 0, 30 },
    { "menu.terminal.next", "terminal", "sessions", "studio.action.terminal.next", "", 0, 40 },
    { "menu.terminal.previous", "terminal", "sessions", "studio.action.terminal.previous", "", 0, 50 },
    { "menu.terminal.execute", "terminal", "commands", "studio.action.terminal.execute", "", 0, 60 },
    { "menu.terminal.search", "terminal", "commands", "studio.action.terminal.search", "", 0, 70 },
    { "menu.terminal.clear", "terminal", "commands", "studio.action.terminal.clear", "", 0, 80 },
    { "menu.terminal.split-horizontal", "terminal", "layout", "studio.action.terminal.split-horizontal", "", 0, 90 },
    { "menu.terminal.split-vertical", "terminal", "layout", "studio.action.terminal.split-vertical", "", 0, 100 },
    { "menu.terminal.history-clear", "terminal", "history", "studio.action.terminal.history-clear", "", 0, 110 },
    { "menu.source-control.refresh", "source-control", "repository", "studio.action.vcs.refresh", "", 0, 10 },
    { "menu.source-control.filter", "source-control", "changes", "studio.action.vcs.filter", "", 0, 15 },
    { "menu.source-control.stage-all", "source-control", "changes", "studio.action.vcs.stage-all", "", 0, 20 },
    { "menu.source-control.unstage-all", "source-control", "changes", "studio.action.vcs.unstage-all", "", 0, 30 },
    { "menu.source-control.commit", "source-control", "changes", "studio.action.vcs.commit-composed", "", 0, 40 },
    { "menu.source-control.fetch", "source-control", "remote", "studio.action.vcs.fetch", "", 0, 50 },
    { "menu.source-control.pull", "source-control", "remote", "studio.action.vcs.pull", "", 0, 60 },
    { "menu.source-control.push", "source-control", "remote", "studio.action.vcs.push", "", 0, 70 },
    { "menu.source-control.history", "source-control", "views", "studio.action.pane.vcs-history", "", 0, 80 },
    { "menu.source-control.commit-pane", "source-control", "views", "studio.action.pane.vcs-commit", "", 0, 90 },
    { "menu.source-control.branches", "source-control", "views", "studio.action.pane.vcs-branches", "", 0, 100 },
    { "menu.source-control.remotes", "source-control", "views", "studio.action.pane.vcs-remotes", "", 0, 110 },
    { "menu.source-control.conflicts", "source-control", "views", "studio.action.pane.vcs-conflicts", "", 0, 120 },
    { "menu.source-control.diff", "source-control", "views", "studio.action.pane.vcs-diff", "", 0, 130 },
    { "menu.source-control.operations", "source-control", "views", "studio.action.pane.vcs-operations", "", 0, 140 },
    { "menu.extensions.refresh", "extensions", "management", "studio.action.extensions.refresh", "", 0, 10 },
    { "menu.extensions.catalogue", "extensions", "views", "studio.action.pane.extension-catalogue", "", 0, 20 },
    { "menu.extensions.permissions", "extensions", "views", "studio.action.pane.extension-permissions", "", 0, 30 },
    { "menu.extensions.audit", "extensions", "views", "studio.action.pane.extension-audit", "", 0, 40 },
    { "menu.ai.refresh", "ai", "management", "studio.action.ai.refresh-health", "", 0, 10 },
    { "menu.ai.new-session", "ai", "sessions", "studio.action.ai.new-session", "", 0, 20 },
    { "menu.ai.save-session", "ai", "sessions", "studio.action.ai.save-session", "", 0, 30 },
    { "menu.ai.workspace", "ai", "views", "studio.action.pane.ai-workspace", "", 0, 40 },
    { "menu.ai.runtimes", "ai", "views", "studio.action.pane.ai-runtimes", "", 0, 50 },
    { "menu.ai.context", "ai", "views", "studio.action.pane.ai-context", "", 0, 60 },
    { "menu.ai.sessions", "ai", "views", "studio.action.pane.ai-sessions", "", 0, 70 },
    { "menu.ai.privacy", "ai", "views", "studio.action.pane.ai-privacy", "", 0, 80 },
    { "menu.products.check-updates", "products", "management", "studio.action.marketplace.check-updates", "", 0, 10 },
    { "menu.products.plan-update", "products", "management", "studio.action.marketplace.plan-update", "", 0, 20 },
    { "menu.products.marketplace", "products", "views", "studio.action.pane.product-marketplace", "", 0, 30 },
    { "menu.products.installed", "products", "views", "studio.action.pane.products-installed", "", 0, 40 },
    { "menu.products.updates", "products", "views", "studio.action.pane.product-updates", "", 0, 50 },
    { "menu.products.transactions", "products", "views", "studio.action.pane.product-transactions", "", 0, 60 },
    { "menu.products.evidence", "products", "views", "studio.action.pane.product-evidence", "", 0, 70 },
    { "menu.trading.refresh", "trading", "workspace", "studio.action.trading.refresh", "", 0, 10 },
    { "menu.trading.environment", "trading", "workspace", "studio.action.trading.set-environment", "", 0, 20 },
    { "menu.trading.filter-instruments", "trading", "market", "studio.action.trading.filter-instruments", "", 0, 30 },
    { "menu.trading.select-instrument", "trading", "market", "studio.action.trading.select-instrument", "", 0, 40 },
    { "menu.trading.side", "trading", "order-ticket", "studio.action.trading.set-side", "", 0, 50 },
    { "menu.trading.type", "trading", "order-ticket", "studio.action.trading.set-type", "", 0, 60 },
    { "menu.trading.quantity", "trading", "order-ticket", "studio.action.trading.set-quantity", "", 0, 70 },
    { "menu.trading.prices", "trading", "order-ticket", "studio.action.trading.set-prices", "", 0, 80 },
    { "menu.trading.preview", "trading", "order-ticket", "studio.action.trading.preview-order", "", 0, 90 },
    { "menu.trading.submit", "trading", "order-ticket", "studio.action.trading.submit-order", "", 0, 100 },
    { "menu.trading.filter-orders", "trading", "orders", "studio.action.trading.filter-orders", "", 0, 110 },
    { "menu.trading.select-order", "trading", "orders", "studio.action.trading.select-order", "", 0, 120 },
    { "menu.trading.cancel-order", "trading", "orders", "studio.action.trading.cancel-order", "", 0, 130 },
    { "menu.trading.kill-switch", "trading", "safety", "studio.action.trading.engage-kill-switch", "", 0, 140 },
    { "menu.trading.reset-kill-switch", "trading", "safety", "studio.action.trading.reset-kill-switch", "", 0, 150 },
    { "menu.trading.dashboard", "trading", "views", "studio.action.pane.trading-dashboard", "", 0, 160 },
    { "menu.trading.watchlist", "trading", "views", "studio.action.pane.trading-watchlist", "", 0, 170 },
    { "menu.trading.depth", "trading", "views", "studio.action.pane.trading-depth", "", 0, 180 },
    { "menu.trading.chart", "trading", "views", "studio.action.pane.trading-chart", "", 0, 190 },
    { "menu.trading.order-ticket", "trading", "views", "studio.action.pane.trading-order-ticket", "", 0, 200 },
    { "menu.trading.orders", "trading", "views", "studio.action.pane.trading-orders", "", 0, 210 },
    { "menu.trading.executions", "trading", "views", "studio.action.pane.trading-executions", "", 0, 220 },
    { "menu.trading.portfolio-risk", "trading", "views", "studio.action.pane.trading-portfolio-risk", "", 0, 230 },
    { "menu.help.about", "help", "about", "studio.action.notification.info", "", 0, 10 }
};

static const UmiUiToolbarSnapshot STUDIO_TOOLBAR[] = {
    { "toolbar.develop", "main", "studio.action.perspective.develop", "perspectives", 0, 10 },
    { "toolbar.build", "main", "studio.action.perspective.build", "perspectives", 0, 20 },
    { "toolbar.test", "main", "studio.action.perspective.test", "perspectives", 0, 30 },
    { "toolbar.separator", "main", "", "layout", 1, 40 },
    { "toolbar.explorer", "main", "studio.action.pane.explorer", "layout", 0, 50 },
    { "toolbar.output", "main", "studio.action.pane.output", "layout", 0, 60 },
    { "toolbar.layout-reset", "main", "studio.action.layout.reset", "layout", 0, 65 },
    { "toolbar.run-separator", "main", "", "run", 1, 70 },
    { "toolbar.debug-start", "main", "studio.action.debug.start", "run", 0, 80 },
    { "toolbar.debug-stop", "main", "studio.action.debug.stop", "run", 0, 90 }
};

static const UmiUiStatusSnapshot STUDIO_STATUS[] = {
    { "studio.status.ready", "Ready", "Studio runtime readiness", "", 100, 1 },
    { "studio.status.workspace", "No workspace", "Current workspace", "", 90, 1 },
    { "studio.status.tasks", "Tasks: 0", "Queued and running tasks", "", 80, 1 },
    { "studio.status.documents", "Documents: 0", "Open documents", "", 70, 1 }
};

static const UmiUiContributionSnapshot STUDIO_CONTRIBUTIONS[] = {
    { "studio.contribution.explorer", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_EXPLORER, 10, 1 },
    { "studio.contribution.editor", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_EDITOR, 20, 1 },
    { "studio.contribution.output", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_OUTPUT, 30, 1 },
    { "studio.contribution.problems", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PROBLEMS, 40, 1 },
    { "studio.contribution.search", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_SEARCH, 50, 1 },
    { "studio.contribution.terminal", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TERMINAL, 55, 1 },
    { "studio.contribution.processes", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PROCESSES, 56, 1 },
    { "studio.contribution.tasks", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TASKS, 57, 1 },
    { "studio.contribution.terminal-history", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TERMINAL_HISTORY, 58, 1 },
    { "studio.contribution.chat", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_CHAT, 60, 1 },
    { "studio.contribution.develop", "org.umicom.studio.shell", "umicom.ui.perspectives", UMI_STUDIO_PERSPECTIVE_DEVELOP, 70, 1 },
    { "studio.contribution.build", "org.umicom.studio.shell", "umicom.ui.perspectives", UMI_STUDIO_PERSPECTIVE_BUILD, 80, 1 },
    { "studio.contribution.source-control", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_SOURCE_CONTROL, 90, 1 },
    { "studio.contribution.vcs-commit", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_COMMIT, 91, 1 },
    { "studio.contribution.vcs-history", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_HISTORY, 92, 1 },
    { "studio.contribution.vcs-branches", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_BRANCHES, 93, 1 },
    { "studio.contribution.vcs-remotes", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_REMOTES, 94, 1 },
    { "studio.contribution.vcs-conflicts", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_CONFLICTS, 95, 1 },
    { "studio.contribution.vcs-diff", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_DIFF, 96, 1 },
    { "studio.contribution.vcs-operations", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_VCS_OPERATIONS, 97, 1 },
    { "studio.contribution.run-debug", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_RUN_DEBUG, 100, 1 },
    { "studio.contribution.debug-call-stack", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_DEBUG_CALL_STACK, 101, 1 },
    { "studio.contribution.debug-variables", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_DEBUG_VARIABLES, 102, 1 },
    { "studio.contribution.debug-watches", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_DEBUG_WATCHES, 103, 1 },
    { "studio.contribution.debug-breakpoints", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_DEBUG_BREAKPOINTS, 104, 1 },
    { "studio.contribution.debug-console", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_DEBUG_CONSOLE, 105, 1 },
    { "studio.contribution.testing", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TESTING, 110, 1 },
    { "studio.contribution.test-results", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TEST_RESULTS, 111, 1 },
    { "studio.contribution.test-failures", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TEST_FAILURES, 112, 1 },
    { "studio.contribution.test-output", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TEST_OUTPUT, 113, 1 },
    { "studio.contribution.test-coverage", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TEST_COVERAGE, 114, 1 },
    { "studio.contribution.test-runs", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TEST_RUNS, 115, 1 },
    { "studio.contribution.build-dashboard", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_BUILD_DASHBOARD, 116, 1 },
    { "studio.contribution.build-graph", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_BUILD_GRAPH, 117, 1 },
    { "studio.contribution.build-history", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_BUILD_HISTORY, 118, 1 },
    { "studio.contribution.build-output", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_BUILD_OUTPUT, 119, 1 },
    { "studio.contribution.build-artifacts", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_BUILD_ARTIFACTS, 120, 1 },
    { "studio.contribution.build-tasks", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_BUILD_TASKS, 121, 1 },
    { "studio.contribution.trading-dashboard", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_DASHBOARD, 122, 1 },
    { "studio.contribution.trading-watchlist", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_WATCHLIST, 123, 1 },
    { "studio.contribution.trading-depth", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_DEPTH, 124, 1 },
    { "studio.contribution.trading-chart", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_CHART, 125, 1 },
    { "studio.contribution.trading-order-ticket", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_ORDER_TICKET, 126, 1 },
    { "studio.contribution.trading-orders", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_ORDERS, 127, 1 },
    { "studio.contribution.trading-executions", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_EXECUTIONS, 128, 1 },
    { "studio.contribution.trading-portfolio-risk", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_TRADING_PORTFOLIO_RISK, 129, 1 },
    { "studio.contribution.designer", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_DESIGNER, 120, 1 },
    { "studio.contribution.applications", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_APPLICATIONS, 130, 1 },
    { "studio.contribution.application-components", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_APPLICATION_COMPONENTS, 131, 1 },
    { "studio.contribution.gtk4-coverage", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_GTK4_COVERAGE, 132, 1 },
    { "studio.contribution.framework", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_FRAMEWORK, 140, 1 },
    { "studio.contribution.ai", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI, 150, 1 },
    { "studio.contribution.ai-runtimes", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_RUNTIMES, 151, 1 },
    { "studio.contribution.ai-context", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_CONTEXT, 152, 1 },
    { "studio.contribution.ai-sessions", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_SESSIONS, 153, 1 },
    { "studio.contribution.ai-privacy", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_PRIVACY, 154, 1 },
    { "studio.contribution.ai-coding", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_CODING, 155, 1 },
    { "studio.contribution.ai-coding-context", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_CODING_CONTEXT, 156, 1 },
    { "studio.contribution.ai-patch-review", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_AI_PATCH_REVIEW, 157, 1 },
    { "studio.contribution.extensions", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_EXTENSIONS, 160, 1 },
    { "studio.contribution.extension-catalogue", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_EXTENSION_CATALOGUE, 161, 1 },
    { "studio.contribution.extension-permissions", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_EXTENSION_PERMISSIONS, 162, 1 },
    { "studio.contribution.extension-audit", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_EXTENSION_AUDIT, 163, 1 },
    { "studio.contribution.product-marketplace", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PRODUCT_MARKETPLACE, 170, 1 },
    { "studio.contribution.products-installed", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PRODUCTS_INSTALLED, 171, 1 },
    { "studio.contribution.product-updates", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PRODUCT_UPDATES, 172, 1 },
    { "studio.contribution.product-transactions", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PRODUCT_TRANSACTIONS, 173, 1 },
    { "studio.contribution.product-evidence", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_PRODUCT_EVIDENCE, 174, 1 }
    ,{ "studio.contribution.knowledge", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_KNOWLEDGE, 180, 1 }
    ,{ "studio.contribution.knowledge-collections", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_KNOWLEDGE_COLLECTIONS, 181, 1 }
    ,{ "studio.contribution.knowledge-sources", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_KNOWLEDGE_SOURCES, 182, 1 }
    ,{ "studio.contribution.knowledge-search", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_KNOWLEDGE_SEARCH, 183, 1 }
    ,{ "studio.contribution.knowledge-source", "org.umicom.studio.shell", "umicom.ui.panes", UMI_STUDIO_PANE_KNOWLEDGE_SOURCE, 184, 1 }
};

UmiStatus umi_studio_contributions_register_layout(UmiUiWorkbench *workbench)
{
    static const UmiUiLayoutNode NODES[] = {
        { "root", "", "", UMI_UI_LAYOUT_ROOT, UMI_UI_HORIZONTAL, 1.0, 0 },
        { "root.horizontal", "root", "", UMI_UI_LAYOUT_SPLIT, UMI_UI_HORIZONTAL, 0.22, 10 },
        { "left.tabs", "root.horizontal", "", UMI_UI_LAYOUT_TABS, UMI_UI_VERTICAL, 1.0, 10 },
        { "left.explorer", "left.tabs", UMI_STUDIO_PANE_EXPLORER, UMI_UI_LAYOUT_PANE, UMI_UI_VERTICAL, 1.0, 10 },
        { "centre.vertical", "root.horizontal", "", UMI_UI_LAYOUT_SPLIT, UMI_UI_VERTICAL, 0.72, 20 },
        { "centre.documents", "centre.vertical", UMI_STUDIO_PANE_EDITOR, UMI_UI_LAYOUT_DOCUMENTS, UMI_UI_VERTICAL, 0.72, 10 },
        { "centre.bottom", "centre.vertical", "", UMI_UI_LAYOUT_TABS, UMI_UI_HORIZONTAL, 0.28, 20 },
        { "bottom.output", "centre.bottom", UMI_STUDIO_PANE_OUTPUT, UMI_UI_LAYOUT_PANE, UMI_UI_HORIZONTAL, 1.0, 10 },
        { "bottom.problems", "centre.bottom", UMI_STUDIO_PANE_PROBLEMS, UMI_UI_LAYOUT_PANE, UMI_UI_HORIZONTAL, 1.0, 20 },
        { "bottom.terminal", "centre.bottom", UMI_STUDIO_PANE_TERMINAL, UMI_UI_LAYOUT_PANE, UMI_UI_HORIZONTAL, 1.0, 30 },
        { "bottom.processes", "centre.bottom", UMI_STUDIO_PANE_PROCESSES, UMI_UI_LAYOUT_PANE, UMI_UI_HORIZONTAL, 1.0, 40 },
        { "bottom.tasks", "centre.bottom", UMI_STUDIO_PANE_TASKS, UMI_UI_LAYOUT_PANE, UMI_UI_HORIZONTAL, 1.0, 50 },
        { "bottom.terminal-history", "centre.bottom", UMI_STUDIO_PANE_TERMINAL_HISTORY, UMI_UI_LAYOUT_PANE, UMI_UI_HORIZONTAL, 1.0, 60 },
        { "right.chat", "root.horizontal", UMI_STUDIO_PANE_CHAT, UMI_UI_LAYOUT_PANE, UMI_UI_VERTICAL, 0.24, 30 }
    };
    size_t index;
    UmiStatus status;
    UmiUiLayout *layout;

    if (workbench == NULL) return UMI_STATUS_INVALID_ARGUMENT;
    layout = umi_ui_workbench_layout(workbench);
    for (index = 0U; index < sizeof(NODES) / sizeof(NODES[0]); ++index) {
        status = umi_ui_layout_upsert(layout, &NODES[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    {
        char validation_message[256];
        return umi_ui_layout_validate(layout, validation_message,
                                      sizeof(validation_message));
    }
}

UmiStatus umi_studio_contributions_register(UmiUiWorkbench *workbench)
{
    size_t index;
    UmiStatus status;

    if (workbench == NULL) return UMI_STATUS_INVALID_ARGUMENT;
    for (index = 0U; index < sizeof(STUDIO_PANES) / sizeof(STUDIO_PANES[0]); ++index) {
        status = umi_ui_pane_model_upsert(umi_ui_workbench_panes(workbench), &STUDIO_PANES[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    for (index = 0U; index < sizeof(STUDIO_ACTIONS) / sizeof(STUDIO_ACTIONS[0]); ++index) {
        status = umi_ui_action_model_upsert(umi_ui_workbench_actions(workbench), &STUDIO_ACTIONS[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    for (index = 0U; index < sizeof(STUDIO_MENUS) / sizeof(STUDIO_MENUS[0]); ++index) {
        status = umi_ui_menu_model_upsert(umi_ui_workbench_menus(workbench), &STUDIO_MENUS[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    for (index = 0U; index < sizeof(STUDIO_TOOLBAR) / sizeof(STUDIO_TOOLBAR[0]); ++index) {
        status = umi_ui_toolbar_model_upsert(umi_ui_workbench_toolbars(workbench), &STUDIO_TOOLBAR[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    for (index = 0U; index < sizeof(STUDIO_STATUS) / sizeof(STUDIO_STATUS[0]); ++index) {
        status = umi_ui_status_model_upsert(umi_ui_workbench_status(workbench), &STUDIO_STATUS[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    for (index = 0U; index < sizeof(STUDIO_CONTRIBUTIONS) / sizeof(STUDIO_CONTRIBUTIONS[0]); ++index) {
        status = umi_ui_contribution_model_upsert(umi_ui_workbench_contributions(workbench), &STUDIO_CONTRIBUTIONS[index]);
        if (status != UMI_STATUS_OK) return status;
    }
    return umi_studio_contributions_register_layout(workbench);
}

size_t umi_studio_contribution_definition_count(void)
{
    return sizeof(STUDIO_CONTRIBUTIONS) / sizeof(STUDIO_CONTRIBUTIONS[0]);
}
