/* Umicom Studio IDE | Sammy Hegab | Umicom Foundation | MIT */
#include "umicom/studio/frontend_studio_commands.h"
#include "umicom/studio/frontend_studio_inspector.h"
#include "umicom/studio/frontend_studio_preview.h"
#include <stdio.h>
#include <string.h>
static const UmiStudioFrontendCommand commands[UMI_STUDIO_FRONTEND_COMMAND_COUNT]={{"frontend.preview.start","Start Frontend Preview",1},{"frontend.preview.stop","Stop Frontend Preview",1},{"frontend.preview.reload","Reload Frontend Preview",1},{"frontend.preview.navigate","Navigate Frontend Preview",1},{"frontend.device.select","Select Responsive Device",1},{"frontend.changes.publish","Publish Frontend Changes",1},{"frontend.inspector.clear","Clear Browser Inspector",1},{"frontend.pane.activate","Activate Frontend Pane",1},{"frontend.snapshot","Show Frontend Snapshot",0}};
size_t umi_studio_frontend_commands_count(void){return UMI_STUDIO_FRONTEND_COMMAND_COUNT;}
const UmiStudioFrontendCommand *umi_studio_frontend_command_at(size_t i){return i<UMI_STUDIO_FRONTEND_COMMAND_COUNT?&commands[i]:NULL;}
UmiStatus umi_studio_frontend_command_execute(UmiStudioFrontendCentre *c,const char *id,const char *arg,char *m,size_t cap){UmiStatus st=UMI_STATUS_NOT_FOUND;uint64_t g=0U;UmiStudioFrontendCentreSnapshot snap;if(c==NULL||id==NULL)return UMI_STATUS_INVALID_ARGUMENT;if(strcmp(id,"frontend.preview.start")==0)st=umi_studio_frontend_preview_start(c->platform);else if(strcmp(id,"frontend.preview.stop")==0)st=umi_studio_frontend_preview_stop(c->platform);else if(strcmp(id,"frontend.preview.reload")==0)st=umi_studio_frontend_preview_reload(c->platform);else if(strcmp(id,"frontend.preview.navigate")==0)st=arg!=NULL?umi_studio_frontend_preview_navigate(c->platform,arg):UMI_STATUS_INVALID_ARGUMENT;else if(strcmp(id,"frontend.device.select")==0)st=arg!=NULL?umi_studio_frontend_preview_select_device(c->platform,arg):UMI_STATUS_INVALID_ARGUMENT;else if(strcmp(id,"frontend.changes.publish")==0)st=umi_studio_frontend_centre_publish(c,&g);else if(strcmp(id,"frontend.inspector.clear")==0){umi_studio_frontend_inspector_clear(c->platform);st=UMI_STATUS_OK;}else if(strcmp(id,"frontend.pane.activate")==0)st=arg!=NULL?umi_studio_frontend_centre_activate(c,arg):UMI_STATUS_INVALID_ARGUMENT;else if(strcmp(id,"frontend.snapshot")==0)st=umi_studio_frontend_centre_snapshot(c,&snap);if(m!=NULL&&cap>0U){if(g>0U)(void)snprintf(m,cap,"Frontend command %s: %s; generation %llu",id,umi_status_text(st),(unsigned long long)g);else (void)snprintf(m,cap,"Frontend command %s: %s",id,umi_status_text(st));}return st;}
