/* Umicom Studio IDE | Polyglot workspace v2 | Sammy Hegab | Umicom Foundation | MIT */
#include "umicom/studio/polyglot_workspace.h"
#include <stdio.h>
#include <string.h>
UmiStatus umi_studio_polyglot_workspace_init(UmiStudioPolyglotWorkspace *workspace,const char *workspace_id,const UmiCompilerProjectManifest *manifest)
{ size_t index; if (workspace == NULL || workspace_id == NULL || workspace_id[0] == '\0' || manifest == NULL) return UMI_STATUS_INVALID_ARGUMENT; (void)memset(workspace,0,sizeof(*workspace)); (void)snprintf(workspace->workspace_id,sizeof(workspace->workspace_id),"%s",workspace_id); workspace->manifest = *manifest; for (index = 0U; index < manifest->unit_count; ++index) workspace->language_mask |= UMI_COMPILER_LANGUAGE_BIT(manifest->units[index].language); if (manifest->unit_count > 0U) (void)snprintf(workspace->active_unit,sizeof(workspace->active_unit),"%s",manifest->units[0].unit_id); workspace->revision = 1U; return UMI_STATUS_OK; }
UmiStatus umi_studio_polyglot_workspace_select_unit(UmiStudioPolyglotWorkspace *workspace,const char *unit_id)
{ if (workspace == NULL || unit_id == NULL) return UMI_STATUS_INVALID_ARGUMENT; if (umi_compiler_manifest_find_unit(&workspace->manifest,unit_id) == NULL) return UMI_STATUS_NOT_FOUND; (void)snprintf(workspace->active_unit,sizeof(workspace->active_unit),"%s",unit_id); workspace->revision += 1U; return UMI_STATUS_OK; }
size_t umi_studio_polyglot_workspace_language_count(const UmiStudioPolyglotWorkspace *workspace) { size_t count = 0U; UmiCompilerLanguage language; if (workspace == NULL) return 0U; for (language = UMI_COMPILER_LANGUAGE_C; language <= UMI_COMPILER_LANGUAGE_UAI; language = (UmiCompilerLanguage)(language + 1)) if ((workspace->language_mask & UMI_COMPILER_LANGUAGE_BIT(language)) != 0U) count += 1U; return count; }
