/* Umicom Studio IDE | Umicc integration v2 | Sammy Hegab | Umicom Foundation | MIT */
#include "umicom/studio/umicc_integration.h"
#include <stdio.h>
#include <string.h>
UmiStatus umi_studio_umicc_integration_configure(UmiStudioUmiccIntegration *integration,const char *executable,const char *version,const char *target,bool local_runtime)
{ if (integration == NULL || executable == NULL || version == NULL || target == NULL || target[0] == '\0') return UMI_STATUS_INVALID_ARGUMENT; (void)memset(integration,0,sizeof(*integration)); (void)snprintf(integration->executable,sizeof(integration->executable),"%s",executable); (void)snprintf(integration->version,sizeof(integration->version),"%s",version); (void)snprintf(integration->target,sizeof(integration->target),"%s",target); integration->language_mask = UINT32_MAX; integration->available = executable[0] != '\0'; integration->local_runtime = local_runtime; integration->stable_c_abi = true; integration->revision = 1U; return UMI_STATUS_OK; }
UmiCompilerProvider umi_studio_umicc_integration_provider(const UmiStudioUmiccIntegration *integration) { return umi_compiler_umicc_provider(integration != NULL ? integration->executable : "",integration != NULL ? integration->target : ""); }
UmiStatus umi_studio_umicc_integration_validate(const UmiStudioUmiccIntegration *integration,char *out_reason,size_t capacity)
{ UmiStatus status = UMI_STATUS_OK; const char *reason = "Umicc integration is ready"; if (integration == NULL || out_reason == NULL || capacity == 0U) return UMI_STATUS_INVALID_ARGUMENT; if (!integration->available) { status = UMI_STATUS_UNAVAILABLE; reason = "Umicc executable is not configured"; } else if (!integration->stable_c_abi) { status = UMI_STATUS_INVALID_STATE; reason = "Stable C ABI support is required"; } (void)snprintf(out_reason,capacity,"%s",reason); return status; }
