/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/status/branch.inc
 * PURPOSE:
 *   GTK status-strip presentation metadata for Framework status kind Branch.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_STATUS_PROFILE(UMI_STUDIO_STATUS_BRANCH, "branch", "Branch")
