/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/status/encoding.inc
 * PURPOSE:
 *   GTK status-strip presentation metadata for Framework status kind Encoding.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_STATUS_PROFILE(UMI_STUDIO_STATUS_ENCODING, "encoding", "Encoding")
