/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/status/language.inc
 * PURPOSE:
 *   GTK status-strip presentation metadata for Framework status kind Language.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_STATUS_PROFILE(UMI_STUDIO_STATUS_LANGUAGE, "language", "Language")
