/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/status/problems.inc
 * PURPOSE:
 *   GTK status-strip presentation metadata for Framework status kind Problems.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_STATUS_PROFILE(UMI_STUDIO_STATUS_PROBLEMS, "problems", "Problems")
