/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/build.inc
 * PURPOSE:
 *   Familiar GTK keyboard entry point for the real Framework command developer.build.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_b, GDK_KEY_B, (GDK_CONTROL_MASK | GDK_SHIFT_MASK), "build.build", "Build")
