/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/debug_stop.inc
 * PURPOSE:
 *   Familiar Visual Studio-style Shift+F5 entry point for the real Framework
 *   debug.stop command.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_F5, GDK_KEY_F5, (GDK_SHIFT_MASK), "debug.stop", "Stop Debugging")
