/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/debug.inc
 * PURPOSE:
 *   Familiar Visual Studio-style F5 entry point for the real Framework
 *   debug.start command.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_F5, GDK_KEY_F5, (0), "debug.start", "Start Debugging")
