/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/go_to_line.inc
 * PURPOSE: Open Framework's source-location form from the Studio keyboard route.
 * AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
 * LICENCE: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_g, GDK_KEY_G, GDK_CONTROL_MASK,
    "umicom.document.go-to-line", "Go to Line")
