/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/layout_browser.inc
 * PURPOSE:
 *   Familiar GTK keyboard entry point for the real Framework command studio.layout.manager.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_l, GDK_KEY_L, (GDK_CONTROL_MASK | GDK_SHIFT_MASK), "studio.layout.manager", "Layouts")
