/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/problems.inc
 * PURPOSE:
 *   Familiar GTK keyboard entry point for the real Framework command view.problems.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_m, GDK_KEY_M, (GDK_CONTROL_MASK | GDK_SHIFT_MASK), "view.problems", "Problems")
