/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: src/gui/workbench/runtime/profiles/keybindings/quick_open.inc
 * PURPOSE: Provide a familiar entry point for indexed-file navigation.
 * AUTHOR AND ORGANISATION: Sammy Hegab, Umicom Foundation
 * LICENCE: MIT
 *---------------------------------------------------------------------------*/

UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_p, GDK_KEY_P, GDK_CONTROL_MASK, "studio.file.quick-open", "Quick Open")
