/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/run.inc
 * PURPOSE:
 *   Familiar Visual Studio-style Ctrl+F5 entry point for the real Framework
 *   run.start command (Run Without Debugging).
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_F5, GDK_KEY_F5, (GDK_CONTROL_MASK), "run.start", "Run Without Debugging")
