/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/source_control.inc
 * PURPOSE:
 *   Familiar GTK keyboard entry point for the real Framework command view.source-control.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_g, GDK_KEY_G, (GDK_CONTROL_MASK | GDK_SHIFT_MASK), "view.source-control", "Source Control")
