/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/terminal.inc
 * PURPOSE:
 *   Familiar GTK keyboard entry point for the real Framework command view.terminal.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_grave, GDK_KEY_asciitilde, (GDK_CONTROL_MASK), "view.terminal", "Terminal")
