/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/gui/workbench/runtime/profiles/keybindings/tests.inc
 * PURPOSE:
 *   Familiar GTK keyboard entry point for the real Framework command view.test-explorer.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
UMI_STUDIO_GTK_KEY_PROFILE(GDK_KEY_t, GDK_KEY_T, (GDK_CONTROL_MASK | GDK_SHIFT_MASK), "view.test-explorer", "Testing")
