# Umicom Studio IDE | Sammy Hegab, Umicom Foundation | MIT
include_guard(GLOBAL)
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../docs/ATTACH_RUNNING_APPLICATION.html"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/umicom-studio/docs")
if(NOT BUILD_TESTING OR NOT TARGET umicom-native-attach-adapter-fixture)
    return()
endif()
add_executable(umicom-studio-native-attach-test "${CMAKE_CURRENT_LIST_DIR}/../tests/test_native_attach.c")
target_link_libraries(umicom-studio-native-attach-test PRIVATE Umicom::StudioCore)
set_target_properties(umicom-studio-native-attach-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
umicom_apply_warnings(umicom-studio-native-attach-test)
umicom_apply_sanitizers(umicom-studio-native-attach-test)
add_dependencies(umicom-studio-native-attach-test umicom-native-attach-adapter-fixture)
if(COMMAND umicom_register_validation_target)
    umicom_register_validation_target(umicom-studio-native-attach-test)
endif()
foreach(case normal denied invalid relative-adapter destroy busy)
    set(directory "${CMAKE_CURRENT_BINARY_DIR}/native-attach/${case}")
    file(MAKE_DIRECTORY "${directory}")
    add_test(NAME studio.debug.attach.service.${case} COMMAND umicom-studio-native-attach-test "${case}"
        "$<TARGET_FILE:umicom-native-attach-adapter-fixture>" "${directory}")
    set_tests_properties(studio.debug.attach.service.${case} PROPERTIES TIMEOUT 60 LABELS "studio;debug;attach;fixture;native-transport")
endforeach()
if(NOT TARGET umicom-studio-workspace-canvas-test)
    return()
endif()
add_executable(umicom-studio-native-attach-gtk4-test
    "${CMAKE_CURRENT_LIST_DIR}/../tests/test_native_attach_gtk4.c"
    "${CMAKE_CURRENT_LIST_DIR}/../src/gui/workbench/workbench_window.c")
target_include_directories(umicom-studio-native-attach-gtk4-test PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/gui/workbench/include")
target_link_libraries(umicom-studio-native-attach-gtk4-test PRIVATE
    Umicom::StudioCore Umicom::ui_gtk4 PkgConfig::GTK4 PkgConfig::GLIB PkgConfig::GIO)
set_target_properties(umicom-studio-native-attach-gtk4-test PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
umicom_apply_warnings(umicom-studio-native-attach-gtk4-test)
umicom_apply_sanitizers(umicom-studio-native-attach-gtk4-test)
add_dependencies(umicom-studio-native-attach-gtk4-test umicom-native-attach-adapter-fixture)
if(COMMAND umicom_register_validation_target)
    umicom_register_validation_target(umicom-studio-native-attach-gtk4-test)
endif()
foreach(case normal denied invalid retained hidden revoke)
    add_test(NAME studio.debug.attach.gtk4.${case} COMMAND umicom-studio-native-attach-gtk4-test "${case}"
        "$<TARGET_FILE:umicom-native-attach-adapter-fixture>")
    set_tests_properties(studio.debug.attach.gtk4.${case} PROPERTIES TIMEOUT 60 SKIP_RETURN_CODE 77 LABELS "studio;debug;attach;fixture;gtk4;ownership")
endforeach()
